### ISSUE TITLE
Getting error in Kedro Spaceflight tutorial while using tags in pipeline definition

### ISSUE THREAD

**Issue by ajit555db** [quantumblacklabs/kedro#148]
## Description
Completed all steps successfully but getting an error in running pipeline using tags:
https://kedro.readthedocs.io/en/latest/03_tutorial/04_create_pipelines.html#using-tags

when tags are applied, "kedro run" or "kedro run --tag=ds_tag" gives below error:
```
TypeError: __init__() got an unexpected keyword argument 'tags'
```

## Context

without tags in pipeline definition, the application runs successfully as below:

```
$ kedro run
2019-10-29 07:42:04,749 - root - INFO - ** Kedro project kedro-tutorial
fatal: not a git repository (or any of the parent directories): .git
2019-10-29 07:42:04,761 - kedro.versioning.journal - WARNING - Unable to git describe /home/ajit/ajit-code/zzztemp/kedro/kedro-site/02-tutorial/kedro-tutorial
2019-10-29 07:42:04,782 - kedro.io.data_catalog - INFO - Loading data from `companies` (CSVLocalDataSet)...
2019-10-29 07:42:04,846 - kedro.pipeline.node - INFO - Running node: preprocess1: preprocess_companies([companies]) -> [preprocessed_companies]
2019-10-29 07:42:04,936 - kedro.io.data_catalog - INFO - Saving data to `preprocessed_companies` (CSVLocalDataSet)...
2019-10-29 07:42:05,482 - kedro.runner.sequential_runner - INFO - Completed 1 out of 6 tasks
2019-10-29 07:42:05,482 - kedro.io.data_catalog - INFO - Loading data from `shuttles` (ExcelLocalDataSet)...
2019-10-29 07:42:23,180 - kedro.pipeline.node - INFO - Running node: preprocess2: preprocess_shuttles([shuttles]) -> [preprocessed_shuttles]
2019-10-29 07:42:23,303 - kedro.io.data_catalog - INFO - Saving data to `preprocessed_shuttles` (CSVLocalDataSet)...
2019-10-29 07:42:24,418 - kedro.runner.sequential_runner - INFO - Completed 2 out of 6 tasks
2019-10-29 07:42:24,418 - kedro.io.data_catalog - INFO - Loading data from `preprocessed_shuttles` (CSVLocalDataSet)...
2019-10-29 07:42:24,601 - kedro.io.data_catalog - INFO - Loading data from `preprocessed_companies` (CSVLocalDataSet)...
2019-10-29 07:42:24,659 - kedro.io.data_catalog - INFO - Loading data from `reviews` (CSVLocalDataSet)...
2019-10-29 07:42:24,753 - kedro.pipeline.node - INFO - Running node: master_table: create_master_table([preprocessed_companies,preprocessed_shuttles,reviews]) -> [master_table]
2019-10-29 07:42:27,359 - kedro.io.data_catalog - INFO - Saving data to `master_table` (CSVLocalDataSet)...
2019-10-29 07:42:49,238 - kedro.runner.sequential_runner - INFO - Completed 3 out of 6 tasks
2019-10-29 07:42:49,238 - kedro.io.data_catalog - INFO - Loading data from `master_table` (CSVLocalDataSet)...
2019-10-29 07:42:52,026 - kedro.io.data_catalog - INFO - Loading data from `parameters` (MemoryDataSet)...
2019-10-29 07:42:52,027 - kedro.pipeline.node - INFO - Running node: split_data([master_table,parameters]) -> [X_test,X_train,y_test,y_train]
2019-10-29 07:42:52,765 - kedro.io.data_catalog - INFO - Saving data to `X_train` (MemoryDataSet)...
2019-10-29 07:42:52,829 - kedro.io.data_catalog - INFO - Saving data to `X_test` (MemoryDataSet)...
2019-10-29 07:42:52,852 - kedro.io.data_catalog - INFO - Saving data to `y_train` (MemoryDataSet)...
2019-10-29 07:42:52,854 - kedro.io.data_catalog - INFO - Saving data to `y_test` (MemoryDataSet)...
2019-10-29 07:42:52,925 - kedro.runner.sequential_runner - INFO - Completed 4 out of 6 tasks
2019-10-29 07:42:52,925 - kedro.io.data_catalog - INFO - Loading data from `X_train` (MemoryDataSet)...
2019-10-29 07:42:52,990 - kedro.io.data_catalog - INFO - Loading data from `y_train` (MemoryDataSet)...
2019-10-29 07:42:52,991 - kedro.pipeline.node - INFO - Running node: train_model([X_train,y_train]) -> [regressor]
2019-10-29 07:42:53,426 - kedro.io.data_catalog - INFO - Saving data to `regressor` (PickleLocalDataSet)...
2019-10-29 07:42:53,606 - kedro.runner.sequential_runner - INFO - Completed 5 out of 6 tasks
2019-10-29 07:42:53,606 - kedro.io.data_catalog - INFO - Loading data from `regressor` (PickleLocalDataSet)...
2019-10-29 07:42:53,607 - kedro.io.data_catalog - INFO - Loading data from `X_test` (MemoryDataSet)...
2019-10-29 07:42:53,624 - kedro.io.data_catalog - INFO - Loading data from `y_test` (MemoryDataSet)...
2019-10-29 07:42:53,625 - kedro.pipeline.node - INFO - Running node: evaluate_model([X_test,regressor,y_test]) -> None
2019-10-29 07:42:53,704 - kedro_tutorial.nodes.price_prediction - INFO - Model has a coefficient R^2 of 0.456.
2019-10-29 07:42:53,760 - kedro.runner.sequential_runner - INFO - Completed 6 out of 6 tasks
2019-10-29 07:42:53,761 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.

```

## Steps to Reproduce

But if tags are placed in the pipeline, and the project is run "kedro run" or "kedro run --tag=ds_tag", I am getting an error as below:

```
    ds_pipeline = Pipeline(
        [
            node(
                split_data,
                ["master_table", "parameters"],
                ["X_train", "X_test", "y_train", "y_test"],
            ),
            node(train_model, ["X_train", "y_train"], "regressor"),
            node(evaluate_model, ["regressor", "X_test", "y_test"], None),
        ],
        tags=["ds_tag"],
    )
```
## Expected Result

The project should run successfully or only pipeline with specified tag should run.

## Actual Result
After using tags in the pipeline, the below error is occurring:

```
$ kedro run
2019-10-29 07:46:47,501 - root - INFO - ** Kedro project kedro-tutorial
Traceback (most recent call last):
  File "/home/ajit/miniconda3/envs/kedro/bin/kedro", line 10, in <module>
    sys.exit(main())
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/kedro/cli/cli.py", line 621, in main
    ("Project specific commands", project_groups),
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ajit/ajit-code/zzztemp/kedro/kedro-site/02-tutorial/kedro-tutorial/kedro_cli.py", line 196, in run
    pipeline_name=pipeline,
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/kedro/context/context.py", line 413, in run
    pipeline = self._get_pipeline(name=pipeline_name)
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/kedro/context/context.py", line 154, in _get_pipeline
    pipelines = self._get_pipelines()
  File "/home/ajit/ajit-code/zzztemp/kedro/kedro-site/02-tutorial/kedro-tutorial/src/kedro_tutorial/run.py", line 51, in _get_pipelines
    return create_pipelines()
  File "/home/ajit/ajit-code/zzztemp/kedro/kedro-site/02-tutorial/kedro-tutorial/src/kedro_tutorial/pipeline.py", line 124, in create_pipelines
    tags=["ds_tag"],
TypeError: __init__() got an unexpected keyword argument 'tags'
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (pip show kedro or kedro -V): 0.15.3
* Python version used (python -V): 3.7.3
* Operating system and version: ubuntu 18.04.03 LTS

**Comment by yetudada** [comment]
Hi @ajit555db! We're so sorry about the error and thank you for raising it. Could you try the argument `name` instead of `tags` and let me know what if you received an error too? 

In any case, I've added this to our internal tracker and we'll address this for our next release.

**Comment by ajit555db** [comment]
@yetudada I did not understand " Could you try the argument name instead of tags and let me know what if you received an error too?"

I tried below:

```
$ kedro run --name=ds_tag
Usage: kedro run [OPTIONS]
Try "kedro run -h" for help.

Error: no such option: --name
```
or 
in pipeline definition:
```
    ds_pipeline = Pipeline(
        [
            node(
                split_data,
                ["master_table", "parameters"],
                ["X_train", "X_test", "y_train", "y_test"],
            ),
            node(train_model, ["X_train", "y_train"], "regressor"),
            node(evaluate_model, ["regressor", "X_test", "y_test"], None),
        ],
        name=["ds_tag"],
    )
```
Then run:
```
$ kedro run --tag=ds_tag
2019-10-30 03:28:40,933 - root - INFO - ** Kedro project kedro-tutorial
Traceback (most recent call last):
  File "/home/ajit/miniconda3/envs/kedro/bin/kedro", line 10, in <module>
    sys.exit(main())
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/kedro/cli/cli.py", line 621, in main
    ("Project specific commands", project_groups),
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ajit/ajit-code/zzztemp/kedro/kedro-site/02-tutorial/kedro-tutorial/kedro_cli.py", line 196, in run
    pipeline_name=pipeline,
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/kedro/context/context.py", line 413, in run
    pipeline = self._get_pipeline(name=pipeline_name)
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/kedro/context/context.py", line 154, in _get_pipeline
    pipelines = self._get_pipelines()
  File "/home/ajit/ajit-code/zzztemp/kedro/kedro-site/02-tutorial/kedro-tutorial/src/kedro_tutorial/run.py", line 51, in _get_pipelines
    return create_pipelines()
  File "/home/ajit/ajit-code/zzztemp/kedro/kedro-site/02-tutorial/kedro-tutorial/src/kedro_tutorial/pipeline.py", line 124, in create_pipelines
    name=["ds_tag"],
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/kedro/pipeline/pipeline.py", line 138, in __init__
    nodes = [n.tag([name]) for n in nodes]
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/kedro/pipeline/pipeline.py", line 138, in <listcomp>
    nodes = [n.tag([name]) for n in nodes]
  File "/home/ajit/miniconda3/envs/kedro/lib/python3.7/site-packages/kedro/pipeline/node.py", line 216, in tag
    tags=set(self._tags) | set(tags),
TypeError: unhashable type: 'list'
```

**Comment by Flid** [comment]
`name` is just one string, `name="ds_tag"` should do the job

**Comment by yetudada** [comment]
@ajit555db We've just released `kedro 0.15.4` which should fix this issue. Please upgrade your project and specify `tags=["ds_tag"]`. Do let me know if this resolves the problem.

**Comment by ajit555db** [comment]
@yetudada awesome, I could successfully run the partial pipeline with the supplied tag!! Many thanks for the quick action.
```
$ kedro --version
kedro, version 0.15.4
(kedro) ajit@inuc7p:~/ajit-code/zzztemp/kedro/kedro-site/02-tutorial/kedro-tutorial
$ kedro run --tag=ds_tag
2019-10-31 01:53:41,868 - root - INFO - ** Kedro project kedro-tutorial
fatal: not a git repository (or any of the parent directories): .git
2019-10-31 01:53:41,883 - kedro.versioning.journal - WARNING - Unable to git describe /home/ajit/ajit-code/zzztemp/kedro/kedro-site/02-tutorial/kedro-tutorial
2019-10-31 01:53:41,904 - kedro.io.data_catalog - INFO - Loading data from `master_table` (CSVLocalDataSet)...
2019-10-31 01:53:44,877 - kedro.io.data_catalog - INFO - Loading data from `parameters` (MemoryDataSet)...
2019-10-31 01:53:44,877 - kedro.pipeline.node - INFO - Running node: split_data([master_table,parameters]) -> [X_test,X_train,y_test,y_train]
2019-10-31 01:53:45,666 - kedro.io.data_catalog - INFO - Saving data to `X_train` (MemoryDataSet)...
2019-10-31 01:53:45,730 - kedro.io.data_catalog - INFO - Saving data to `X_test` (MemoryDataSet)...
2019-10-31 01:53:45,746 - kedro.io.data_catalog - INFO - Saving data to `y_train` (MemoryDataSet)...
2019-10-31 01:53:45,750 - kedro.io.data_catalog - INFO - Saving data to `y_test` (MemoryDataSet)...
2019-10-31 01:53:45,819 - kedro.runner.sequential_runner - INFO - Completed 1 out of 3 tasks
2019-10-31 01:53:45,820 - kedro.io.data_catalog - INFO - Loading data from `X_train` (MemoryDataSet)...
2019-10-31 01:53:45,883 - kedro.io.data_catalog - INFO - Loading data from `y_train` (MemoryDataSet)...
2019-10-31 01:53:45,884 - kedro.pipeline.node - INFO - Running node: train_model([X_train,y_train]) -> [regressor]
2019-10-31 01:53:46,331 - kedro.io.data_catalog - INFO - Saving data to `regressor` (PickleLocalDataSet)...
2019-10-31 01:53:46,510 - kedro.runner.sequential_runner - INFO - Completed 2 out of 3 tasks
2019-10-31 01:53:46,511 - kedro.io.data_catalog - INFO - Loading data from `regressor` (PickleLocalDataSet)...
2019-10-31 01:53:46,512 - kedro.io.data_catalog - INFO - Loading data from `X_test` (MemoryDataSet)...
2019-10-31 01:53:46,536 - kedro.io.data_catalog - INFO - Loading data from `y_test` (MemoryDataSet)...
2019-10-31 01:53:46,537 - kedro.pipeline.node - INFO - Running node: evaluate_model([X_test,regressor,y_test]) -> None
2019-10-31 01:53:46,618 - kedro_tutorial.nodes.price_prediction - INFO - Model has a coefficient R^2 of 0.456.
2019-10-31 01:53:46,667 - kedro.runner.sequential_runner - INFO - Completed 3 out of 3 tasks
2019-10-31 01:53:46,667 - kedro.runner.sequential_runner - INFO - Pipeline execution completed successfully.
```

**Comment by yetudada** [comment]
🏆 Thanks for reporting the error @ajit555db! And I'm glad you're sorted!

**Comment by YYx00xZZ** [comment]
You have done really really awesome work. Kedro stands out! I would say i've never seen framework of this kind. However, I stumbled upon an error while I was going to enjoy Kedro.
## Description
When running ```kedro new --starter=spaceflights  ``` and after i have filled the initial project info, when I run ```kedro install``` i'm getting this error ```TypeError: _validate_items() got an unexpected keyword argument 'only'```
I'm on _5.13.13-1-MANJARO_ and I have Python3.9.6 installed as system one. To be able to use kedro I use pipenv in collab with pyenv
## steps to reproduce
```
    ~  mkdir test_drive_kedro; cd $_                                       ✔ 
    ~/test_drive_kedro  export PIPENV_VENV_IN_PROJECT=1                    ✔ 
    ~/test_drive_kedro  pipenv install --python 3.8                        ✔ 
Creating a virtualenv for this project...
Pipfile: /home/alexander/test_drive_kedro/Pipfile
Using /home/alexander/.pyenv/versions/3.8.12/bin/python3.8 (3.8.12) to create virtualenv...
⠼ Creating virtual environment...created virtual environment CPython3.8.12.final.0-64 in 184ms
  creator CPython3Posix(dest=/home/alexander/test_drive_kedro/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/alexander/.local/share/virtualenv)
    added seed packages: pip==21.2.4, setuptools==57.4.0, wheel==0.37.0
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/alexander/test_drive_kedro/.venv
Creating a Pipfile for this project...
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Updated Pipfile.lock (db4242)!
Installing dependencies from Pipfile.lock (db4242)...
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
    ~/test_drive_kedro  pipenv shell                                       ✔ 
Launching subshell in virtual environment...
 . /home/alexander/test_drive_kedro/.venv/bin/activate
    ~/test_drive_kedro   . /home/alexander/test_drive_kedro/.venv/bin/activate
    ~/test_drive_kedro  python -m pip install kedro   ✔  test_drive_kedro  
Collecting kedro
  Using cached kedro-0.17.4-py3-none-any.whl (17.4 MB)
Collecting anyconfig~=0.10.0
  Using cached anyconfig-0.10.1-py2.py3-none-any.whl (64 kB)
Collecting gitpython~=3.0
  Using cached GitPython-3.1.18-py3-none-any.whl (170 kB)
Collecting python-json-logger~=2.0
  Using cached python_json_logger-2.0.2-py3-none-any.whl (7.4 kB)
Collecting PyYAML<6.0,>=4.2
  Using cached PyYAML-5.4.1-cp38-cp38-manylinux1_x86_64.whl (662 kB)
Collecting toml~=0.10
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting cachetools~=4.1
  Using cached cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting cookiecutter~=1.7.0
  Using cached cookiecutter-1.7.3-py2.py3-none-any.whl (34 kB)
Collecting pip-tools~=5.0
  Using cached pip_tools-5.5.0-py2.py3-none-any.whl (45 kB)
Collecting jupyter-client<7.0,>=5.1
  Using cached jupyter_client-6.1.12-py3-none-any.whl (112 kB)
Collecting toposort~=1.5
  Using cached toposort-1.6-py2.py3-none-any.whl (9.5 kB)
Collecting pluggy~=0.13.0
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting fsspec<0.9,>=0.5.1
  Using cached fsspec-0.8.7-py3-none-any.whl (103 kB)
Collecting dynaconf~=3.1.2
  Using cached dynaconf-3.1.7-py2.py3-none-any.whl (200 kB)
Collecting click<8.0
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting jmespath<1.0,>=0.9.5
  Using cached jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Requirement already satisfied: setuptools>=38.0 in ./.venv/lib/python3.8/site-packages (from kedro) (57.4.0)
Collecting binaryornot>=0.4.4
  Using cached binaryornot-0.4.4-py2.py3-none-any.whl (9.0 kB)
Collecting requests>=2.23.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting python-slugify>=4.0.0
  Using cached python_slugify-5.0.2-py2.py3-none-any.whl (6.7 kB)
Collecting jinja2-time>=0.2.0
  Using cached jinja2_time-0.2.0-py2.py3-none-any.whl (6.4 kB)
Collecting poyo>=0.5.0
  Using cached poyo-0.5.0-py2.py3-none-any.whl (10 kB)
Collecting six>=1.10
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting Jinja2<4.0.0,>=2.7
  Using cached Jinja2-3.0.1-py3-none-any.whl (133 kB)
Collecting chardet>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting gitdb<5,>=4.0.1
  Using cached gitdb-4.0.7-py3-none-any.whl (63 kB)
Collecting smmap<5,>=3.0.1
  Using cached smmap-4.0.0-py2.py3-none-any.whl (24 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.0.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)
Collecting arrow
  Using cached arrow-1.1.1-py3-none-any.whl (60 kB)
Collecting traitlets
  Using cached traitlets-5.1.0-py3-none-any.whl (101 kB)
Collecting jupyter-core>=4.6.0
  Using cached jupyter_core-4.7.1-py3-none-any.whl (82 kB)
Collecting tornado>=4.1
  Using cached tornado-6.1-cp38-cp38-manylinux2010_x86_64.whl (427 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pyzmq>=13
  Using cached pyzmq-22.2.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
Requirement already satisfied: pip>=20.1 in ./.venv/lib/python3.8/site-packages (from pip-tools~=5.0->kedro) (21.2.4)
Collecting text-unidecode>=1.3
  Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.2-py3-none-any.whl (59 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
Installing collected packages: six, python-dateutil, MarkupSafe, urllib3, traitlets, text-unidecode, smmap, Jinja2, idna, charset-normalizer, chardet, certifi, arrow, tornado, requests, pyzmq, python-slugify, poyo, jupyter-core, jinja2-time, gitdb, click, binaryornot, toposort, toml, PyYAML, python-json-logger, pluggy, pip-tools, jupyter-client, jmespath, gitpython, fsspec, dynaconf, cookiecutter, cachetools, anyconfig, kedro
Successfully installed Jinja2-3.0.1 MarkupSafe-2.0.1 PyYAML-5.4.1 anyconfig-0.10.1 arrow-1.1.1 binaryornot-0.4.4 cachetools-4.2.2 certifi-2021.5.30 chardet-4.0.0 charset-normalizer-2.0.4 click-7.1.2 cookiecutter-1.7.3 dynaconf-3.1.7 fsspec-0.8.7 gitdb-4.0.7 gitpython-3.1.18 idna-3.2 jinja2-time-0.2.0 jmespath-0.10.0 jupyter-client-6.1.12 jupyter-core-4.7.1 kedro-0.17.4 pip-tools-5.5.0 pluggy-0.13.1 poyo-0.5.0 python-dateutil-2.8.2 python-json-logger-2.0.2 python-slugify-5.0.2 pyzmq-22.2.1 requests-2.26.0 six-1.16.0 smmap-4.0.0 text-unidecode-1.3 toml-0.10.2 toposort-1.6 tornado-6.1 traitlets-5.1.0 urllib3-1.26.6
    ~/test_drive_kedro  kedro new --starter=spaceflights

Project Name:
=============
Please enter a human readable name for your new project.
Spaces and punctuation are allowed.
 [New Kedro Project]: Test Drive kedro

Repository Name:
================
Please enter a directory name for your new project repository.
Alphanumeric characters, hyphens and underscores are allowed.
Lowercase is recommended.
 [test-drive-kedro]: 

Python Package Name:
====================
Please enter a valid Python package name for your project package.
Alphanumeric characters and underscores are allowed.
Lowercase is recommended. Package name must start with a letter
or underscore.
 [test_drive_kedro]: 

Change directory to the project generated in /home/alexander/test_drive_kedro/test-drive-kedro

A best-practice setup includes initialising git and creating a virtual environment before running ``kedro install`` to install project-specific dependencies. Refer to the Kedro documentation: https://kedro.readthedocs.io/
    ~/test_drive_kedro  cd test-drive-kedro   ✔  48s   test_drive_kedro  
    ~/t/test-drive-kedro  kedro install               ✔  test_drive_kedro  
Traceback (most recent call last):
  File "/home/alexander/test_drive_kedro/.venv/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/home/alexander/test_drive_kedro/.venv/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 264, in main
    cli_collection = KedroCLI(project_path=Path.cwd())
  File "/home/alexander/test_drive_kedro/.venv/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 182, in __init__
    self._metadata = bootstrap_project(project_path)
  File "/home/alexander/test_drive_kedro/.venv/lib/python3.8/site-packages/kedro/framework/startup.py", line 184, in bootstrap_project
    configure_project(metadata.package_name)
  File "/home/alexander/test_drive_kedro/.venv/lib/python3.8/site-packages/kedro/framework/project/__init__.py", line 219, in configure_project
    settings.configure(settings_module)
  File "/home/alexander/test_drive_kedro/.venv/lib/python3.8/site-packages/dynaconf/base.py", line 182, in configure
    self._wrapped = Settings(settings_module=settings_module, **kwargs)
  File "/home/alexander/test_drive_kedro/.venv/lib/python3.8/site-packages/dynaconf/base.py", line 235, in __init__
    self.validators.validate(
  File "/home/alexander/test_drive_kedro/.venv/lib/python3.8/site-packages/dynaconf/validator.py", line 417, in validate
    validator.validate(self.settings, only=only, exclude=exclude)
  File "/home/alexander/test_drive_kedro/.venv/lib/python3.8/site-packages/dynaconf/validator.py", line 197, in validate
    self._validate_items(
TypeError: _validate_items() got an unexpected keyword argument 'only'
    ~/t/test-drive-kedro                            1 ✘  test_drive_kedro  

```

**Comment by mzjp2** [comment]
@YYx00xZZ See this issue (and the related solution: pin Dynaconf to 3.1.5) :)
