### ISSUE TITLE
SparkJDBCDataSet: Catch empty credential values before py4j does

### ISSUE THREAD

**Issue by tamsanh** [quantumblacklabs/kedro#192]
## Description

The error message that appears when an empty credential property gets passed into SparkJDBCDataSet is rather opaque and caused my coworker and I an embarrassingly long time to figure out that our credential file was simply missing a value, ie. it was being sent to py4j as `None`.

What follows is the original exception that is thrown by `py4j`.

```
kedro.io.core.DataSetError: Failed while loading data from data set SparkJDBCDataSet(load_args={'properties': {'driver': com.mysql.jdbc.Driver}}, save_args={'properties': {'driver': com.mysql.jdbc.Driver}}, table=cust_ctct_info, url=jdbc:mysql://127.0.0.1:33064/raw).
An error occurred while calling o59.setProperty.
: java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at java.util.Properties.setProperty(Properties.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

What would be great is to catch the `None` before it gets into `py4j` and becomes a dreaded `NullPointerException`.

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

Would just like to help prevent this for others in the future, to save them time from a silly problem.

**Comment by yetudada** [comment]
This issue was closed with #194. Thank you for raising this!
