### ISSUE TITLE
[KED-1474] SparkSession initialized when using parallel runner throws random errors

### ISSUE THREAD

**Issue by adengappa** [quantumblacklabs/kedro#287]
## Description
I'm trying to use Kedro's parallel runner to parallelize a few independent pipelines in my set of pipelines which have only sparkDatasets as input. Unfortunately  unable to do so since parallel runner with a pre established sparkSession. or spark-submit.

## Context
How has this bug affected you? What were you trying to accomplish?
Trying to achieve parallelism when possible in my set of pipelines.
Set of pipelines I have run as expected when I use sequentialRunner. I have used both kedro cli and spark-submit and both these ways work just fine.
but when I use parallel runner, in spite of all intermediate results being persisted - execution stops soon after loading my first dataset returning me inconsistent/random errors. 
This happens specifically if sparkSession is initialized in run.py as mentioned in the documentation. 

## Steps to Reproduce
1. setup at least 2 SparkDatasets in catalog
2. Define a simple node that reads and writes(also a sparkDataset) for a pipeline that can run in parallel for 2 datasets
3. Initialize sparkSession in run.py
4. Execute the pipeline with parallel runner

## Expected Result
Execution be parallel and should complete without any issues. eg: 2 output files be created

## Actual Result
A random set of errors are thrown from the execution. 

There errors are in no order.
Same execution gives random errors in no order

##############################################################################################################
    return SparkSession.builder.getOrCreate()
  File "/usr/hdp/current/spark2-client/python/lib/pyspark.zip/pyspark/sql/session.py", line 183, in getOrCreate
    session._jsparkSession.sessionState().conf().setConfString(key, value)
AttributeError: 'NoneType' object has no attribute 'conf'
###############################################################################################################
WARN FileStreamSink: Error while looking for metadata directory.
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/user.name/.local/lib/python3.6/site-packages/kedro/io/core.py", line 194, in load
    return self._load()
  File "/home/user.name/.local/lib/python3.6/site-packages/kedro/contrib/io/pyspark/spark_data_set.py", line 246, in _load
    load_path, self._file_format, **self._load_args
  File "/home/user.name/.local/lib/python3.6/site-packages/pyspark/sql/readwriter.py", line 166, in load
    return self._df(self._jreader.load(path))
AttributeError: 'NoneType' object has no attribute 'load'
##################################################################################################################
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/user.name/.local/lib/python3.6/site-packages/kedro/runner/runner.py", line 180, in run_node
    inputs = {name: catalog.load(name) for name in node.inputs}
  File "/home/user.name/.local/lib/python3.6/site-packages/kedro/runner/runner.py", line 180, in <dictcomp>
    inputs = {name: catalog.load(name) for name in node.inputs}
  File "/home/user.name/.local/lib/python3.6/site-packages/kedro/io/data_catalog.py", line 318, in load
    result = func()
  File "/home/user.name/.local/lib/python3.6/site-packages/kedro/io/core.py", line 560, in load
    return super().load()
  File "/home/user.name/.local/lib/python3.6/site-packages/kedro/io/core.py", line 203, in load
    raise DataSetError(message) from exc
kedro.io.core.DataSetError: Failed while loading data from data set SparkDataSet(file_format=parquet, filepath=s3a://abc/file/).
'NoneType' object has no attribute 'load'

######################################################################################################################
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/sriram_ravichandran/.virtualenvs/test/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/Users/sriram_ravichandran/.virtualenvs/test/lib/python3.7/site-packages/kedro/cli/cli.py", line 638, in main
    ("Project specific commands", project_groups),
  File "/Users/sriram_ravichandran/.virtualenvs/test/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sriram_ravichandran/.virtualenvs/test/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/sriram_ravichandran/.virtualenvs/test/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sriram_ravichandran/.virtualenvs/test/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sriram_ravichandran/.virtualenvs/test/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/sriram_ravichandran/dev/odysseyDemo/kedro_cli.py", line 274, in run
    pipeline_name=pipeline,
  File "/Users/sriram_ravichandran/.virtualenvs/test/lib/python3.7/site-packages/kedro/context/context.py", line 479, in run
    return runner.run(filtered_pipeline, catalog)
  File "/Users/sriram_ravichandran/.virtualenvs/test/lib/python3.7/site-packages/kedro/runner/runner.py", line 82, in run
    self._run(pipeline, catalog)
  File "/Users/sriram_ravichandran/.virtualenvs/test/lib/python3.7/site-packages/kedro/runner/parallel_runner.py", line 259, in _run
    node = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
KeyError: 'c'

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

env1
* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.5
* Python version used (`python -V`): 3.6.3
* Operating system and version: RHEL7
* Spark : 2.3.2

env2
* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.5
* Python version used (`python -V`): 3.7.5
* Operating system and version: Mac Catalina
* Spark : 2.4.5

**Comment by yetudada** [comment]
Thanks for reporting this error! @adengappa, I've put it on our backlog to look into.

**Comment by andrii-ivaniuk** [comment]
ThreadRunner was added to run Spark dataset concurrently.

**Comment by 921kiyo** [comment]
Implemented in https://github.com/quantumblacklabs/kedro/commit/c79c21a50924b2f79f1207de167b27d7c7e8bef0
