### ISSUE TITLE
Incompatible python-dateutil version with Kedro Viz

### ISSUE THREAD

**Issue by flvndh** [quantumblacklabs/kedro#361]
## Context
Initializing a new Kedro project.

## Environment
- Windows 10
- Python 3.7.7
- Conda 4.7.12
- Pip 20.0.2
- Kedro 0.15.9

## Steps to Reproduce
```
conda create -n removeme python=3.7
conda activate removeme
pip install kedro==0.15.9
kedro new
cd new-kedro-project
kedro install
````

```
ERROR: kedro-viz 3.2.0 has requirement python-dateutil==2.8.0, but you'll have python-dateutil 2.8.1 which is incompatible.
```

## Side Effects

```
kedro activate-nbstripout
```

```
Traceback (most recent call last):
  File ".miniconda3/envs/removeme/lib/python3.7/site-packages/kedro/cli/cli.py", line 594, in load_entry_points
    entry_point_commands.append(entry_point.load())
  File ".miniconda3/envs/removeme/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File ".miniconda3/envs/removeme/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File ".miniconda3/envs/removeme/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (python-dateutil 2.8.1 (.miniconda3/envs/removeme/lib/python3.7/site-packages), Requirement.parse('python-dateutil==2.8.0'))
Error: Loading global commands from kedro-viz = kedro_viz.server:commands
Notebook output cells will be automatically cleared before committing to git.
nbstripout --install
```

**Comment by yetudada** [comment]
Hey @flvndh! Thanks for raising this issue. We actually have a fix coming for this in the next releases of Kedro-Viz, see it [**here**](https://github.com/quantumblacklabs/kedro-viz/commit/c577dffb095333df3f8cd5d811d8647a16f89990). Stay tuned because they're out soon. 

I'll close this issue because it's fixed but I'm interested, do you use `kedro activate-nbstripout` in your workflow?
