### ISSUE TITLE
Kedro can't build requirements with newest pip (v20.1)

### ISSUE THREAD

**Issue by markf94** [quantumblacklabs/kedro#374]
## Description
`kedro build-reqs` fails when using the newest pip version `20.1`. However, it does work fine with pip version `19.3.1` (you can easily check by running `pip install pip==19.3.1`).

## Context
`pip` told me I should update to version `20.1` which I did with `pip install --upgrade pip`. Afterwards, I added some new requirements to `src/requirements.in` in my `kedro` project and wanted to to build the requirements by running `kedro build-reqs`.

## Steps to Reproduce
1. Initialize a kedro repo
2. Create a Python virtual environment within the kedro repo (`python3 -m venv .venv`)
3. Activate the virtual environment (`source .venv/bin/activate`)
3. Upgrade pip to `20.1` with `python -m pip install --upgrade pip`
4. Add some requirements and run `kedro build-reqs`

## Expected Result
I expect the successful building of my `requirements.txt` file with a final output line like this:

```
Requirements built! Please update requirements.in if you'd like to make a change in your project's dependencies, and re-run build-reqs to generate the new requirements.txt.
```

## Actual Result
Instead of building the requirements the command `kedro build-reqs` fails with the following traceback:

```
/home/markf94/.../kedro-project/.venv/bin/python -m piptools compile /home/markf94/.../kedro-project/src/requirements.in
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/markf94/.../kedro-project/.venv/lib/python3.7/site-packages/piptools/__main__.py", line 17, in <module>
    cli()
  File "/home/markf94/.../kedro-project/.venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/markf94/.../kedro-project/.venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/markf94/.../kedro-project/.venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/markf94/.../kedro-project/.venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/markf94.../kedro-project/.venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/markf94/.../kedro-project/.venv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/markf94/.../kedro-project/.venv/lib/python3.7/site-packages/piptools/scripts/compile.py", line 304, in cli
    for ireq in filter(is_pinned_requirement, ireqs):
  File "/home/markf94/.../kedro-project/.venv/lib/python3.7/site-packages/piptools/utils.py", line 122, in is_pinned_requirement
    if ireq.editable:
AttributeError: 'ParsedRequirement' object has no attribute 'editable'
```

## My Environment

* Kedro version used (`pip show kedro` or `kedro -V`): `0.15.9`
* Python version used (`python -V`): `3.7.5`
* Pip version used: `20.1`
* Operating system and version: Fedora 31

**Comment by mzjp2** [comment]
Hi @markf94 👋, thanks for reporting this!

I believe the error here stems from the version of `pip-tools` we have in our requirements being incompatible with `pip>=20.0`..

We actually have a fix for this in `develop` that increase the lower bounds for `pip-tools` to `>=5.0` to ensure compatibility with `pip>=20.0` as well as documenting the need for `pip>=20.0` in the migration guide.

The relevant commit is here https://github.com/quantumblacklabs/kedro/commit/56742ff829b0a7943232dc5294086ef25a6d0b09 and we’re planning a release in the span of days.

**Comment by markf94** [comment]
Hi @mzjp2! Thanks for the fast reply. I'm just staying on pip `19.3.1` until you are working on the release.

**Comment by mzjp2** [comment]
Awesome. This should be fixed imminently, so I'll go ahead and close this. Thank you for raising the issue! :)
