### ISSUE TITLE
FileNotFoundError occurs during `kedro jupyter convert` when `source_path / context.package_name / "nodes"` does not exist

### ISSUE THREAD

**Issue by kaemo** [quantumblacklabs/kedro#469]
## Description
As per title, `FileNotFoundError` occurs during `kedro jupyter convert` when `source_path / context.package_name / "nodes"` does not exist. 

## Context
I deleted the `source_path / context.package_name / "nodes"` directory at the beginning of the project because I wasn't using it. Later I created a notebook to try out the notebook-to-nodes conversion functionality but it failed with the aforementioned error.

## Steps to Reproduce
1. Remove `source_path / context.package_name / "nodes"` directory.
2. Create a notebook and tag a cell with a function with `node`.
3. Run `kedro jupyter convert notebooks/<notebook-name>.ipynb`
4. Observe error.

## Expected Result

```
Converting notebook '/Users/olszewk2/dev/pyzypad-example/notebooks/mlp.ipynb'...
Done!
```

## Actual Result

```
Converting notebook '/Users/olszewk2/dev/pyzypad-example/notebooks/mlp.ipynb'...
Traceback (most recent call last):
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 628, in main
    cli_collection()
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/framework/cli/jupyter.py", line 237, in convert_notebook
    _export_nodes(notebook, output_path)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/site-packages/kedro/framework/cli/jupyter.py", line 317, in _export_nodes
    output_path.write_text("")
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/pathlib.py", line 1235, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors) as f:
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/pathlib.py", line 1203, in open
    opener=self._opener)
  File "/Users/olszewk2/miniconda3/envs/pyzypad-example-env/lib/python3.7/pathlib.py", line 1058, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/olszewk2/dev/pyzypad-example/src/pyzypad_example/nodes/mlp.py'
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): kedro, version 0.16.1
* Python version used (`python -V`): Python 3.7.7
* Operating system and version: macOS Mojave Version 10.14.6

**Comment by kaemo** [comment]
I can make a fix and create a PR for this.

**Comment by mzjp2** [comment]
I believe this behaviour has changed in Kedro 0.16.3 onwards, where the nodes folder is created on the fly if it doesn’t exist. You can get this fix by updating to Kedro 0.16.3 :)

**Comment by kaemo** [comment]
@mzjp2 thanks for the information. I'll update to the newest version and report back.

**Comment by 921kiyo** [comment]
Closing this, but feel free to reopen it if you are still getting the error.
