### ISSUE TITLE
Loading data from Github - Error Tokenizing data 

### ISSUE THREAD

**Issue by kelandrin** [quantumblacklabs/kedro#572]
I am trying to load data from a Github that updates daily. 

**Catalog entry looks like this:**

confirmed_us_infections:
  type: pandas.CSVDataSet
  filepath: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv

When I read in the csv without using kedro I have no issues and don't have to specify additional parameters. 
When I read in the csv with kedro I get the following error...

**I get this error:**

kedro.io.core.DataSetError: Failed while loading data from data set CSVDataSet(filepath=github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv, load_args={}, protocol=https, save_args={'index': False}).

**Error tokenizing data. C error: Expected 1 fields in line 51, saw 2**

I have looked at the file on line 51 and did not see anything wrong, but perhaps I am missing something?

**Comment by deepyaman** [comment]
You should point to the [raw file](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv).

Even if you use pandas directly here, you'll face the same issue:

```python
(kedro) BOS-178551-C02X31K9JHD4:kedro deepyaman$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> pd.read_csv("https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/kedro/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/anaconda3/envs/kedro/lib/python3.7/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)
  File "/anaconda3/envs/kedro/lib/python3.7/site-packages/pandas/io/parsers.py", line 1154, in read
    ret = self._engine.read(nrows)
  File "/anaconda3/envs/kedro/lib/python3.7/site-packages/pandas/io/parsers.py", line 2048, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 879, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 894, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 948, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 935, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2130, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 51, saw 2

>>> pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")
           UID iso2 iso3  code3     FIPS      Admin2 Province_State Country_Region        Lat  ...  10/10/20 10/11/20  10/12/20  10/13/20  10/14/20  10/15/20  10/16/20  10/17/20  10/18/20
0     84001001   US  USA    840   1001.0     Autauga        Alabama             US  32.539527  ...      1898     1905      1911      1924      1928      1949      1966      1983      1989
1     84001003   US  USA    840   1003.0     Baldwin        Alabama             US  30.727750  ...      6190     6203      6220      6248      6270      6285      6333      6350      6369
2     84001005   US  USA    840   1005.0     Barbour        Alabama             US  31.868263  ...       942      942       944       951       950       965       968       977       981
3     84001007   US  USA    840   1007.0        Bibb        Alabama             US  32.996421  ...       726      736       738       744       744       761       771       775       785
4     84001009   US  USA    840   1009.0      Blount        Alabama             US  33.982109  ...      1704     1713      1722      1742      1750      1768      1783      1807      1827
...        ...  ...  ...    ...      ...         ...            ...            ...        ...  ...       ...      ...       ...       ...       ...       ...       ...       ...       ...
3335  84056039   US  USA    840  56039.0       Teton        Wyoming             US  43.935225  ...       658      662       675       679       686       687       692       692       700
3336  84056041   US  USA    840  56041.0       Uinta        Wyoming             US  41.287818  ...       379      380       381       384       385       388       392       401       401
3337  84090056   US  USA    840  90056.0  Unassigned        Wyoming             US   0.000000  ...         0        0         0         0         0         0         0         0         0
3338  84056043   US  USA    840  56043.0    Washakie        Wyoming             US  43.904516  ...       124      125       126       127       132       132       133       133       134
3339  84056045   US  USA    840  56045.0      Weston        Wyoming             US  43.839612  ...        58       58        58        62        66        71        81        88        93

[3340 rows x 282 columns]
>>> 
```

**Comment by kelandrin** [comment]
Gotcha, now I am getting URL not found error 

kedro.io.core.DataSetError: Failed while loading data from data set CSVDataSet(filepath=raw.githubusercontent.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv, load_args={}, protocol=https, save_args={'index': False}).
404 Client Error: Not Found for url: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv

**Comment by limdauto** [comment]
@kelandrin Apologies for the late reply. I think the URL you used is incorrect. The correct URL is https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv

Note that there is no `tree/` before `master/` in the correct URL. I will close this ticket but please feel free to reopen it if you still need support.

**Comment by gregmansio** [comment]
Thank you for the solution!
