### ISSUE TITLE
`kedro install` does not install packages added to requirements.txt into virtual environment

### ISSUE THREAD

**Issue by clstaudt** [quantumblacklabs/kedro#589]
## Description

I tried to install dependencies into a virtual environment via `kedro install`. The additional packages I added were not installed. 

## Steps to Reproduce
1. edit requirements.txt - content:

```
black==v19.10b0
flake8>=3.7.9, <4.0
ipython>=7.0.0, <8.0
isort>=4.3.21, <5.0
jupyter
jupyter_client
jupyterlab
kedro==0.16.2
nbstripout==0.3.3
pytest-cov>=2.5, <3.0
pytest-mock>=1.7.1,<2.0
pytest>=5.0, <6.0
wheel==0.32.2
numpy
pandas
matplotlib
seaborn

```
2.  create and activate virtual environment

```
~/D/F/P/Client  virtualenv env-packaging
created virtual environment CPython3.7.8.final.0-64 in 273ms
 creator CPython3Posix(dest=/Users/cls/Documents/Work/Projects/Client/env-packaging, clear=False, global=False)
 seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/cls/Library/Application Support/virtualenv)
   added seed packages: pip==20.2.4, setuptools==50.3.2, wheel==0.35.1
 activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
~/D/F/P/Client  . env-packaging/bin/activate.fish                                                                                                              (463ms)  


```

3. run `kedro install` from the Kedro project folder

```
(env-packaging)  ◰³ env-packaging  ~/D/F/P/H/packaging-estimator  kedro install
Traceback (most recent call last):
 File "/opt/anaconda3/lib/python3.7/site-packages/kedro/framework/cli/cli.py", line 591, in load_entry_points
   entry_point_commands.append(entry_point.load())
 File "/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2471, in load
   self.require(*args, **kwargs)
 File "/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2494, in require
   items = working_set.resolve(reqs, env, installer, extras=self.extras)
 File "/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 790, in resolve
   raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (jupyter-client 6.1.7 (/opt/anaconda3/lib/python3.7/site-packages), Requirement.parse('jupyter-client<6.0,>=5.1.0'), {'kedro'})
Error: Loading global commands from kedro-viz = kedro_viz.server:commands
/opt/anaconda3/bin/python3.7 -m pip install -U -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt
Requirement already up-to-date: black==v19.10b0 in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 1)) (19.10b0)
Requirement already up-to-date: flake8<4.0,>=3.7.9 in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 2)) (3.8.4)
Requirement already up-to-date: ipython<8.0,>=7.0.0 in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (7.18.1)
Requirement already up-to-date: isort<5.0,>=4.3.21 in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 4)) (4.3.21)
Requirement already up-to-date: jupyter in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (1.0.0)
Requirement already up-to-date: jupyter_client in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 6)) (6.1.7)
Requirement already up-to-date: jupyterlab in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 7)) (2.2.9)
Requirement already up-to-date: kedro==0.16.2 in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (0.16.2)
Requirement already up-to-date: nbstripout==0.3.3 in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 9)) (0.3.3)
Requirement already up-to-date: pytest-cov<3.0,>=2.5 in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 10)) (2.10.1)
Requirement already up-to-date: pytest-mock<2.0,>=1.7.1 in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 11)) (1.13.0)
Requirement already up-to-date: pytest<6.0,>=5.0 in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 12)) (5.4.3)
Requirement already up-to-date: wheel==0.32.2 in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 13)) (0.32.2)
Requirement already up-to-date: numpy in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 14)) (1.19.2)
Requirement already up-to-date: pandas in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 15)) (1.1.3)
Requirement already up-to-date: matplotlib in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 16)) (3.3.2)
Requirement already up-to-date: seaborn in /opt/anaconda3/lib/python3.7/site-packages (from -r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 17)) (0.11.0)
Requirement already satisfied, skipping upgrade: regex in /opt/anaconda3/lib/python3.7/site-packages (from black==v19.10b0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 1)) (2020.10.23)
Requirement already satisfied, skipping upgrade: click>=6.5 in /opt/anaconda3/lib/python3.7/site-packages (from black==v19.10b0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 1)) (7.1.2)
Requirement already satisfied, skipping upgrade: appdirs in /opt/anaconda3/lib/python3.7/site-packages (from black==v19.10b0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 1)) (1.4.3)
Requirement already satisfied, skipping upgrade: attrs>=18.1.0 in /opt/anaconda3/lib/python3.7/site-packages (from black==v19.10b0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 1)) (20.2.0)
Requirement already satisfied, skipping upgrade: pathspec<1,>=0.6 in /opt/anaconda3/lib/python3.7/site-packages (from black==v19.10b0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 1)) (0.8.0)
Requirement already satisfied, skipping upgrade: typed-ast>=1.4.0 in /opt/anaconda3/lib/python3.7/site-packages (from black==v19.10b0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 1)) (1.4.1)
Requirement already satisfied, skipping upgrade: toml>=0.9.4 in /opt/anaconda3/lib/python3.7/site-packages (from black==v19.10b0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 1)) (0.10.1)
Requirement already satisfied, skipping upgrade: pyflakes<2.3.0,>=2.2.0 in /opt/anaconda3/lib/python3.7/site-packages (from flake8<4.0,>=3.7.9->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 2)) (2.2.0)
Requirement already satisfied, skipping upgrade: mccabe<0.7.0,>=0.6.0 in /opt/anaconda3/lib/python3.7/site-packages (from flake8<4.0,>=3.7.9->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 2)) (0.6.1)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_version < "3.8" in /opt/anaconda3/lib/python3.7/site-packages (from flake8<4.0,>=3.7.9->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 2)) (2.0.0)
Requirement already satisfied, skipping upgrade: pycodestyle<2.7.0,>=2.6.0a1 in /opt/anaconda3/lib/python3.7/site-packages (from flake8<4.0,>=3.7.9->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 2)) (2.6.0)
Requirement already satisfied, skipping upgrade: traitlets>=4.2 in /opt/anaconda3/lib/python3.7/site-packages (from ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (5.0.5)
Requirement already satisfied, skipping upgrade: pickleshare in /opt/anaconda3/lib/python3.7/site-packages (from ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (0.7.5)
Requirement already satisfied, skipping upgrade: pexpect>4.3; sys_platform != "win32" in /opt/anaconda3/lib/python3.7/site-packages (from ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (4.8.0)
Requirement already satisfied, skipping upgrade: jedi>=0.10 in /opt/anaconda3/lib/python3.7/site-packages (from ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (0.14.1)
Requirement already satisfied, skipping upgrade: setuptools>=18.5 in /opt/anaconda3/lib/python3.7/site-packages (from ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (49.6.0.post20200814)
Requirement already satisfied, skipping upgrade: backcall in /opt/anaconda3/lib/python3.7/site-packages (from ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (0.2.0)
Requirement already satisfied, skipping upgrade: decorator in /opt/anaconda3/lib/python3.7/site-packages (from ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (4.4.2)
Requirement already satisfied, skipping upgrade: pygments in /opt/anaconda3/lib/python3.7/site-packages (from ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (2.6.1)
Requirement already satisfied, skipping upgrade: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/anaconda3/lib/python3.7/site-packages (from ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (3.0.6)
Requirement already satisfied, skipping upgrade: appnope; sys_platform == "darwin" in /opt/anaconda3/lib/python3.7/site-packages (from ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (0.1.0)
Requirement already satisfied, skipping upgrade: notebook in /opt/anaconda3/lib/python3.7/site-packages (from jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (6.1.3)
Requirement already satisfied, skipping upgrade: nbconvert in /opt/anaconda3/lib/python3.7/site-packages (from jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (5.6.1)
Requirement already satisfied, skipping upgrade: qtconsole in /opt/anaconda3/lib/python3.7/site-packages (from jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (4.7.6)
Requirement already satisfied, skipping upgrade: ipywidgets in /opt/anaconda3/lib/python3.7/site-packages (from jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (7.5.1)
Requirement already satisfied, skipping upgrade: ipykernel in /opt/anaconda3/lib/python3.7/site-packages (from jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (5.3.4)
Requirement already satisfied, skipping upgrade: jupyter-console in /opt/anaconda3/lib/python3.7/site-packages (from jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (6.2.0)
Requirement already satisfied, skipping upgrade: pyzmq>=13 in /opt/anaconda3/lib/python3.7/site-packages (from jupyter_client->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 6)) (19.0.2)
Requirement already satisfied, skipping upgrade: tornado>=4.1 in /opt/anaconda3/lib/python3.7/site-packages (from jupyter_client->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 6)) (6.0.4)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in /opt/anaconda3/lib/python3.7/site-packages (from jupyter_client->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 6)) (2.8.1)
Requirement already satisfied, skipping upgrade: jupyter-core>=4.6.0 in /opt/anaconda3/lib/python3.7/site-packages (from jupyter_client->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 6)) (4.6.3)
Requirement already satisfied, skipping upgrade: jinja2>=2.10 in /opt/anaconda3/lib/python3.7/site-packages (from jupyterlab->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 7)) (2.11.2)
Requirement already satisfied, skipping upgrade: jupyterlab-server<2.0,>=1.1.5 in /opt/anaconda3/lib/python3.7/site-packages (from jupyterlab->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 7)) (1.2.0)
Requirement already satisfied, skipping upgrade: anyconfig<1.0,>=0.9.7 in /opt/anaconda3/lib/python3.7/site-packages (from kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (0.9.10)
Requirement already satisfied, skipping upgrade: pluggy<1.0.0,>=0.13.0 in /opt/anaconda3/lib/python3.7/site-packages (from kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (0.13.1)
Requirement already satisfied, skipping upgrade: cookiecutter<1.7.0,>=1.6.0 in /opt/anaconda3/lib/python3.7/site-packages (from kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (1.6.0)
Requirement already satisfied, skipping upgrade: python-json-logger<1.0,>=0.1.9 in /opt/anaconda3/lib/python3.7/site-packages (from kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (0.1.11)
Requirement already satisfied, skipping upgrade: fsspec<0.7.0,>=0.5.1 in /opt/anaconda3/lib/python3.7/site-packages (from kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (0.6.3)
Requirement already satisfied, skipping upgrade: pip-tools<6.0,>=5.0.0 in /opt/anaconda3/lib/python3.7/site-packages (from kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (5.3.1)
Requirement already satisfied, skipping upgrade: jmespath<1.0,>=0.9.5 in /opt/anaconda3/lib/python3.7/site-packages (from kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (0.10.0)
Requirement already satisfied, skipping upgrade: PyYAML<6.0,>=4.2 in /opt/anaconda3/lib/python3.7/site-packages (from kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (5.3.1)
Requirement already satisfied, skipping upgrade: toposort<2.0,>=1.5 in /opt/anaconda3/lib/python3.7/site-packages (from kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (1.5)
Requirement already satisfied, skipping upgrade: cachetools<5.0,>=4.1.0 in /opt/anaconda3/lib/python3.7/site-packages (from kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (4.1.1)
Requirement already satisfied, skipping upgrade: nbformat in /opt/anaconda3/lib/python3.7/site-packages (from nbstripout==0.3.3->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 9)) (5.0.7)
Requirement already satisfied, skipping upgrade: coverage>=4.4 in /opt/anaconda3/lib/python3.7/site-packages (from pytest-cov<3.0,>=2.5->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 10)) (5.3)
Requirement already satisfied, skipping upgrade: wcwidth in /opt/anaconda3/lib/python3.7/site-packages (from pytest<6.0,>=5.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 12)) (0.2.5)
Requirement already satisfied, skipping upgrade: packaging in /opt/anaconda3/lib/python3.7/site-packages (from pytest<6.0,>=5.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 12)) (20.4)
Requirement already satisfied, skipping upgrade: py>=1.5.0 in /opt/anaconda3/lib/python3.7/site-packages (from pytest<6.0,>=5.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 12)) (1.9.0)
Requirement already satisfied, skipping upgrade: more-itertools>=4.0.0 in /opt/anaconda3/lib/python3.7/site-packages (from pytest<6.0,>=5.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 12)) (8.4.0)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /opt/anaconda3/lib/python3.7/site-packages (from pandas->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 15)) (2020.1)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in /opt/anaconda3/lib/python3.7/site-packages (from matplotlib->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 16)) (2.4.7)
Requirement already satisfied, skipping upgrade: pillow>=6.2.0 in /opt/anaconda3/lib/python3.7/site-packages (from matplotlib->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 16)) (7.2.0)
Requirement already satisfied, skipping upgrade: certifi>=2020.06.20 in /opt/anaconda3/lib/python3.7/site-packages (from matplotlib->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 16)) (2020.6.20)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in /opt/anaconda3/lib/python3.7/site-packages (from matplotlib->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 16)) (1.2.0)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in /opt/anaconda3/lib/python3.7/site-packages (from matplotlib->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 16)) (0.10.0)
Requirement already satisfied, skipping upgrade: scipy>=1.0 in /Users/cls/.local/lib/python3.7/site-packages (from seaborn->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 17)) (1.4.1)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /opt/anaconda3/lib/python3.7/site-packages (from importlib-metadata; python_version < "3.8"->flake8<4.0,>=3.7.9->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 2)) (3.1.0)
Requirement already satisfied, skipping upgrade: ipython-genutils in /opt/anaconda3/lib/python3.7/site-packages (from traitlets>=4.2->ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (0.2.0)
Requirement already satisfied, skipping upgrade: ptyprocess>=0.5 in /opt/anaconda3/lib/python3.7/site-packages (from pexpect>4.3; sys_platform != "win32"->ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (0.6.0)
Requirement already satisfied, skipping upgrade: parso>=0.5.0 in /opt/anaconda3/lib/python3.7/site-packages (from jedi>=0.10->ipython<8.0,>=7.0.0->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 3)) (0.5.2)
Requirement already satisfied, skipping upgrade: prometheus-client in /opt/anaconda3/lib/python3.7/site-packages (from notebook->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (0.8.0)
Requirement already satisfied, skipping upgrade: terminado>=0.8.3 in /opt/anaconda3/lib/python3.7/site-packages (from notebook->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (0.9.1)
Requirement already satisfied, skipping upgrade: Send2Trash in /opt/anaconda3/lib/python3.7/site-packages (from notebook->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (1.5.0)
Requirement already satisfied, skipping upgrade: argon2-cffi in /opt/anaconda3/lib/python3.7/site-packages (from notebook->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (20.1.0)
Requirement already satisfied, skipping upgrade: entrypoints>=0.2.2 in /opt/anaconda3/lib/python3.7/site-packages (from nbconvert->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (0.3)
Requirement already satisfied, skipping upgrade: pandocfilters>=1.4.1 in /opt/anaconda3/lib/python3.7/site-packages (from nbconvert->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (1.4.2)
Requirement already satisfied, skipping upgrade: mistune<2,>=0.8.1 in /opt/anaconda3/lib/python3.7/site-packages (from nbconvert->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (0.8.4)
Requirement already satisfied, skipping upgrade: bleach in /opt/anaconda3/lib/python3.7/site-packages (from nbconvert->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (3.1.5)
Requirement already satisfied, skipping upgrade: defusedxml in /opt/anaconda3/lib/python3.7/site-packages (from nbconvert->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (0.6.0)
Requirement already satisfied, skipping upgrade: testpath in /opt/anaconda3/lib/python3.7/site-packages (from nbconvert->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (0.4.4)
Requirement already satisfied, skipping upgrade: qtpy in /opt/anaconda3/lib/python3.7/site-packages (from qtconsole->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (1.9.0)
Requirement already satisfied, skipping upgrade: widgetsnbextension~=3.5.0 in /opt/anaconda3/lib/python3.7/site-packages (from ipywidgets->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (3.5.1)
Requirement already satisfied, skipping upgrade: six>=1.5 in /opt/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.1->jupyter_client->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 6)) (1.15.0)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /opt/anaconda3/lib/python3.7/site-packages (from jinja2>=2.10->jupyterlab->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 7)) (1.1.1)
Requirement already satisfied, skipping upgrade: requests in /opt/anaconda3/lib/python3.7/site-packages (from jupyterlab-server<2.0,>=1.1.5->jupyterlab->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 7)) (2.23.0)
Requirement already satisfied, skipping upgrade: json5 in /opt/anaconda3/lib/python3.7/site-packages (from jupyterlab-server<2.0,>=1.1.5->jupyterlab->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 7)) (0.9.4)
Requirement already satisfied, skipping upgrade: jsonschema>=3.0.1 in /opt/anaconda3/lib/python3.7/site-packages (from jupyterlab-server<2.0,>=1.1.5->jupyterlab->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 7)) (3.0.2)
Requirement already satisfied, skipping upgrade: future>=0.15.2 in /opt/anaconda3/lib/python3.7/site-packages (from cookiecutter<1.7.0,>=1.6.0->kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (0.18.2)
Requirement already satisfied, skipping upgrade: binaryornot>=0.2.0 in /opt/anaconda3/lib/python3.7/site-packages (from cookiecutter<1.7.0,>=1.6.0->kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (0.4.4)
Requirement already satisfied, skipping upgrade: whichcraft>=0.4.0 in /opt/anaconda3/lib/python3.7/site-packages (from cookiecutter<1.7.0,>=1.6.0->kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (0.6.1)
Requirement already satisfied, skipping upgrade: poyo>=0.1.0 in /opt/anaconda3/lib/python3.7/site-packages (from cookiecutter<1.7.0,>=1.6.0->kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (0.5.0)
Requirement already satisfied, skipping upgrade: jinja2-time>=0.1.0 in /opt/anaconda3/lib/python3.7/site-packages (from cookiecutter<1.7.0,>=1.6.0->kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (0.2.0)
Requirement already satisfied, skipping upgrade: pip>=20.0 in /opt/anaconda3/lib/python3.7/site-packages (from pip-tools<6.0,>=5.0.0->kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (20.2.2)
Requirement already satisfied, skipping upgrade: cffi>=1.0.0 in /opt/anaconda3/lib/python3.7/site-packages (from argon2-cffi->notebook->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (1.14.1)
Requirement already satisfied, skipping upgrade: webencodings in /opt/anaconda3/lib/python3.7/site-packages (from bleach->nbconvert->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (0.5.1)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/anaconda3/lib/python3.7/site-packages (from requests->jupyterlab-server<2.0,>=1.1.5->jupyterlab->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 7)) (1.25.10)
Requirement already satisfied, skipping upgrade: chardet<4,>=3.0.2 in /opt/anaconda3/lib/python3.7/site-packages (from requests->jupyterlab-server<2.0,>=1.1.5->jupyterlab->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 7)) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in /opt/anaconda3/lib/python3.7/site-packages (from requests->jupyterlab-server<2.0,>=1.1.5->jupyterlab->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 7)) (2.10)
Requirement already satisfied, skipping upgrade: pyrsistent>=0.14.0 in /opt/anaconda3/lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server<2.0,>=1.1.5->jupyterlab->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 7)) (0.16.0)
Requirement already satisfied, skipping upgrade: arrow in /opt/anaconda3/lib/python3.7/site-packages (from jinja2-time>=0.1.0->cookiecutter<1.7.0,>=1.6.0->kedro==0.16.2->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 8)) (0.17.0)
Requirement already satisfied, skipping upgrade: pycparser in /opt/anaconda3/lib/python3.7/site-packages (from cffi>=1.0.0->argon2-cffi->notebook->jupyter->-r /Users/cls/Documents/Work/Projects/Client/packaging-estimator/src/requirements.txt (line 5)) (2.20)
Requirements installed!
```

## Expected Result

Added requirements, e.g. `pandas`, should be available in virtualenv python.

## Actual Result

```
(env-packaging)  ◰³ env-packaging  ~/D/F/P/H/packaging-estimator  python                                                                                    (6s 541ms)  
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:37:09) 
[Clang 10.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pandas'
```

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`):  kedro, version 0.16.2
* Python version used (`python -V`): Python 3.7.8 
* Operating system and version: macOS 10.15.7

**Comment by DmitriiDeriabinQB** [comment]
It seems that you are using different Python interpreters when running `kedro install` command and when running Python shell. There is a line `Requirement already up-to-date: pandas in /opt/anaconda3/lib/python3.7/site-packages ...` in `kedro install` command output, which indicates that the package is already installed in the environment, which the current interpreter (`/opt/anaconda3/bin/python3.7`) points to. I suspect Kedro is installed using your global Conda interpreter (path from the previous sentence), while `python` points to something else (you can run `which python` to retrieve it).

To make sure Kedro CLI commands are run using the current Python interpreter, you can execute `python -m kedro install`. You'll need to make sure the right version of Kedro is installed in the environment beforehand.

**Comment by lorenabalan** [comment]
I'm closing this as answered but feel free to re-raise / raise a new issue if you're still having trouble with this.

**Comment by clstaudt** [comment]
@lorenabalan Sorry, didn't have time to validate the answer yet, but it's on my list.
