### ISSUE TITLE
kedro new with iris starter not working on windows. 

### ISSUE THREAD

**Issue by Iarwa1n** [quantumblacklabs/kedro#719]
I tried to run

    kedro new --starter=pandas-iris

on two different Windows 10 machines. I created a new conda env with python 3.7 and kedro in it. 
I got the error below. I hope this does not mean that I need admin priviliges for this because I don't have them on one of the machines. :

Traceback (most recent call last):
  File "c:\users\<someusername>\anaconda3\envs\kedro\lib\site-packages\kedro\framework\cli\cli.py", line 300, in _create_project
    config = _prompt_user_for_config(template_path, checkout, directory)
  File "c:\users\<someusername>\anaconda3\envs\kedro\lib\site-packages\kedro\framework\cli\cli.py", line 385, in _prompt_user_for_config
    return config
  File "c:\users\<someusername>\anaconda3\envs\kedro\lib\tempfile.py", line 807, in __exit__
    self.cleanup()
  File "c:\users\<someusername>\anaconda3\envs\kedro\lib\tempfile.py", line 811, in cleanup
    _shutil.rmtree(self.name)
  File "c:\users\<someusername>\anaconda3\envs\kedro\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\<someusername>\anaconda3\envs\kedro\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\<someusername>\anaconda3\envs\kedro\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\<someusername>\anaconda3\envs\kedro\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "c:\users\<someusername>\anaconda3\envs\kedro\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\users\<someusername>\anaconda3\envs\kedro\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Zugriff verweigert: 'C:\\Users\\<someusername>\\AppData\\Local\\Temp\\tmpip55khi2\\kedro-starters\\.git\\objects\\pack\\pack-88c0bc5fd542c1c61726b4836eb1612bf740e5ad.idx'

**Comment by MerelTheisenQB** [comment]
Hi @Iarwa1n, thanks for reporting this. Which version of Kedro are you using?

**Comment by Galileo-Galilei** [comment]
Sorry, I just duplicated this issue in #722. I explain why it does not work with reference. 

For the OP, the current fix is to upgrade to python=3.8.x, but the design decision on how to support previous python version is up to kedro team and unfortunately does not seem straightforward since it is a known bug of python 3.7, not of kedro.

**Comment by MerelTheisenQB** [comment]
Thanks @Galileo-Galilei! @Iarwa1n , I'll close this issue in favour of #722. I hope that's okay 🙂
