### ISSUE TITLE
Poorly formatted credentials.yml throws a confusing error message

### ISSUE THREAD

**Issue by WaylonWalker** [quantumblacklabs/kedro#732]
## Description

Poorly formatted `conf/local/credentials.yml` caused a very confusing error to be thrown by kedro.  Somewhere along this traceback kedro should catch the `AttributeError` and return a custom error message instructing the user to which config file is not properly formatted.

This is probably a super weird edge case, but could cause someone some pain and suffering if they didn't see the call to `_get_config_credentials()`

I created a simplified project so that you can easily see the issue [here](https://github.com/WaylonWalker/vigilant-octo-lamp).  Look at the git history to see the steps to reproduce.

## Error message

Executing `kedro run` results in the following error.

``` python 
2021-03-22 15:49:21,394 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.
2021-03-22 15:49:21,492 - root - INFO - ** Kedro project poor_local_conf
2021-03-22 15:49:21,498 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.
Traceback (most recent call last):
  File "/home/kedro/miniconda3/envs/poor-local-conf/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/home/kedro/miniconda3/envs/poor-local-conf/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 228, in main
    cli_collection(**cli_context)
  File "/home/kedro/miniconda3/envs/poor-local-conf/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/kedro/miniconda3/envs/poor-local-conf/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/kedro/miniconda3/envs/poor-local-conf/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kedro/miniconda3/envs/poor-local-conf/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kedro/miniconda3/envs/poor-local-conf/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/kedro/git/poor_local_conf/src/poor_local_conf/cli.py", line 231, in run
    session.run(
  File "/home/kedro/miniconda3/envs/poor-local-conf/lib/python3.8/site-packages/kedro/framework/session/session.py", line 371, in run
    catalog = context._get_catalog(
  File "/home/kedro/miniconda3/envs/poor-local-conf/lib/python3.8/site-packages/kedro/framework/context/context.py", line 374, in _get_catalog
    conf_creds = self._get_config_credentials()
  File "/home/kedro/miniconda3/envs/poor-local-conf/lib/python3.8/site-packages/kedro/framework/context/context.py", line 491, in _get_config_credentials
    conf_creds = self.config_loader.get(
  File "/home/kedro/miniconda3/envs/poor-local-conf/lib/python3.8/site-packages/kedro/config/config.py", line 226, in get
    new_conf = self._load_configs(config_filepaths)
  File "/home/kedro/miniconda3/envs/poor-local-conf/lib/python3.8/site-packages/kedro/config/config.py", line 164, in _load_configs
    single_config = self._load_config_file(config_filepath)
  File "/home/kedro/miniconda3/envs/poor-local-conf/lib/python3.8/site-packages/kedro/config/config.py", line 141, in _load_config_file
    for k, v in anyconfig.load(config_file).items()
AttributeError: 'str' object has no attribute 'items'

```

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce
_[see example repo](https://github.com/WaylonWalker/vigilant-octo-lamp)_
1. kedro new
2. add sample node
3. add badconf in `conf/local/credentials.yml`

## Expected Result

Kedro should throw an error that lets me know that the credentials file has an issue, the current error message does not tell the story very well.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.2
* Python version used (`python -V`): 3.8
* Operating system and version: Ubuntu

**Comment by lorenabalan** [comment]
Hi @WaylonWalker , thanks for raising this, and for including such a thoughtful way of reproducing/seeing the issue. I've added a ticket on our backlog, but we welcome a PR on this if anyone is keen. 😊

**Comment by lorenabalan** [comment]
Closing this as resolved in https://github.com/quantumblacklabs/kedro/commit/be3022ecf9ea18f6a448ef9d2c57bd8ad089c769 , and will be available in the next release. :) Thank you again for the suggestion!
