### ISSUE TITLE
Running a specific node using tags in 0.17.2

### ISSUE THREAD

**Issue by roumail** [quantumblacklabs/kedro#733]
## Introduction

I'm looking to run a specific node, following instructions [here], for testing purposes. Not sure I'd need to register this pipeline to be able to do that..
(https://kedro.readthedocs.io/en/stable/06_nodes_and_pipelines/01_nodes.html?highlight=tags#how-to-tag-a-node). Anyhow, I created a new environment and started a new project using `kedro new pandas-iris`. 
Next I added an example pipeline with a node I'd like to test using tags.

I add the following line to `src/{{ project name }}/pipelines/data_science/pipeline.py`:
`def test_pipeline(**kwargs): return Pipeline([node(lambda x: x,"example_train_x","example_model",name="test",tags="test")]`

Next, I try to run the specific node using `kedro run --tag test` and get the error
![image](https://user-images.githubusercontent.com/32498483/112096939-7beb2100-8b9f-11eb-8d47-f53131eaa484.png)

## Question

Is there something I'm missing here? Do I need to follow certain steps after generating pandas-iris, specific to pipeline registry? How can I run the nodes tagged with test? 
I think the default pipeline error may be linked to [this](https://github.com/quantumblacklabs/kedro/issues/731)

**Comment by WaylonWalker** [comment]
The error you are seeing is due to improperly formatted pipelines dictionary, or a missing `register_pipelines` function.

Are you using `pipeline_registry.py` or `hooks.py`?

Look in either of those modules for a function called `register_pipelines`.  It should return a dictionary of pipelines, one must be found under the key `__default__`

**Comment by WaylonWalker** [comment]
Whether this turns out as user error or not the Error message here is quite confusing and not very helpful.

If I render a new kedro template with `0l17.2` and delete my `pipeline_registry.py` module I get the same error.  In this case the error should guide the user to create a `register_pipelines` function in the appropriate module

If I rename `__default__` to `new` I get the same error.  In this case the error should make its best attempt to guide the user to the module with the `register_pipelines` function and add a `__default__` key.

**Comment by roumail** [comment]
Thanks for your comments. I actually didn't change anything other than the test pipeline I added to `src/{{ project name }}/pipelines/data_science/pipeline.py`.

I was under the assumption that if I'm on 0.17.2 and I do `kedro new pandas-iris`, the boilerplate code would already be in place to allow a `kedro run`. That doesn't seem to be the case -- the error message as you mention is also not very helpful...

Let me post the directory structure that I have:
```
.                                         
├── conf                                  
│   ├── base                              
│   └── local                             
├── data                                  
│   ├── 01_raw                            
│   ├── 02_intermediate                   
│   ├── 03_primary                        
│   ├── 04_feature                        
│   ├── 05_model_input                    
│   ├── 06_models                         
│   ├── 07_model_output                   
│   └── 08_reporting                      
├── docs                                  
│   └── source                            
├── logs                                  
│   └── journals                          
├── notebooks                             
└── src                                   
    ├── check_tags                        
    │   ├── pipelines                     
    │   │   ├── data_engineering          
    │   │   │   └── __pycache__           
    │   │   ├── data_science              
    │   │   └── __pycache__               
    │   └── __pycache__                   
    └── tests                             
        └── pipelines                     
                                          
27 directories                            
```

**Comment by WaylonWalker** [comment]
What is in your `pipeline_registry.py` file?  It seems like it might be the source of your error message.

> How I can run the test_pipeline using tags/node name?


The help text can guide you to how to run a pipeline from the cli.

```
❯ kedro run --help
Usage: kedro run [OPTIONS]

  Run the pipeline.

Options:
  --from-inputs TEXT        A list of dataset names which should be used as a
                            starting point.

  --to-outputs TEXT         A list of dataset names which should be used as an
                            end point.

  --from-nodes TEXT         A list of node names which should be used as a
                            starting point.

  --to-nodes TEXT           A list of node names which should be used as an
                            end point.

  -n, --node TEXT           Run only nodes with specified names.
  -r, --runner TEXT         Specify a runner that you want to run the pipeline
                            with. Available runners: `SequentialRunner`,
                            `ParallelRunner` and `ThreadRunner`. This option
                            cannot be used together with --parallel.

  -p, --parallel            Run the pipeline using the `ParallelRunner`. If
                            not specified, use the `SequentialRunner`. This
                            flag cannot be used together with --runner.

  --async                   Load and save node inputs and outputs
                            asynchronously with threads. If not specified,
                            load and save datasets synchronously.

  -e, --env TEXT            Kedro configuration environment name. Defaults to
                            `local`.

  -t, --tag TEXT            Construct the pipeline using only nodes which have
                            this tag attached. Option can be used multiple
                            times, what results in a pipeline constructed from
                            nodes having any of those tags.

  -lv, --load-version TEXT  Specify a particular dataset version (timestamp)
                            for loading.

  --pipeline TEXT           Name of the modular pipeline to run. If not set,
                            the project pipeline is run by default.

  -c, --config FILE         Specify a YAML configuration file to load the run
                            command arguments from. If command line arguments
                            are provided, they will override the loaded ones.

  --params TEXT             Specify extra parameters that you want to pass to
                            the context initializer. Items must be separated
                            by comma, keys - by colon, example:
                            param1:value1,param2:value2. Each parameter is
                            split by the first comma, so parameter values are
                            allowed to contain colons, parameter keys are not.

  -h, --help                Show this message and exit.
```

in your case you are looking for the following.  I tried them on the pandas-iris starter and they work after tagging a node as `my_node`


```
# make pandas-iris starter project
kedro new --starter pandas-iris
cd kedro-pandas-iris

# run nodes tagged with "my_tag"
kedro run --tag my_tag
kedro run -t my_tag

# run nodes named "split"
kedro run --node split
kedro run -n split
```

**Comment by roumail** [comment]
Hello again @WaylonWalker, sorry for the delayed reply.. Pasting contents of pipeline_registry and hooks.py below:
## hooks.py
```
"""Project hooks."""
from typing import Any, Dict, Iterable, Optional

from kedro.config import ConfigLoader
from kedro.framework.hooks import hook_impl
from kedro.io import DataCatalog
from kedro.versioning import Journal


class ProjectHooks:
    @hook_impl
    def register_config_loader(
        self, conf_paths: Iterable[str], env: str, extra_params: Dict[str, Any]
    ) -> ConfigLoader:
        return ConfigLoader(conf_paths)

    @hook_impl
    def register_catalog(
        self,
        catalog: Optional[Dict[str, Dict[str, Any]]],
        credentials: Dict[str, Dict[str, Any]],
        load_versions: Dict[str, str],
        save_version: str,
        journal: Journal,
    ) -> DataCatalog:
        return DataCatalog.from_config(
            catalog, credentials, load_versions, save_version, journal
        )
```

## pipeline_registry.py
```
"""Project pipelines."""
from typing import Dict

from kedro.pipeline import Pipeline

from check_tags.pipelines import data_engineering as de
from check_tags.pipelines import data_science as ds


def register_pipelines() -> Dict[str, Pipeline]:
    """Register the project's pipelines.

    Returns:
        A mapping from a pipeline name to a ``Pipeline`` object.

    """
    data_engineering_pipeline = de.create_pipeline()
    data_science_pipeline = ds.create_pipeline()

    return {
        "de": data_engineering_pipeline,
        "ds": data_science_pipeline,
        "__default__": data_engineering_pipeline + data_science_pipeline,
    }
```

## new pipeline I added to the ds pipeline
```
"""Example code for the nodes in the example pipeline. This code is meant                                                   
just for illustrating basic Kedro features.                                                                                 
                                                                                                                            
Delete this when you start working on your own Kedro project.                                                               
"""                                                                                                                         
                                                                                                                            
from kedro.pipeline import Pipeline, node                                                                                   
                                                                                                                            
from .nodes import predict, report_accuracy, train_model                                                                    
                                                                                                                            
                                                                                                                            
def create_pipeline(**kwargs):                                                                                              
    return Pipeline(                                                                                                        
        [                                                                                                                   
            node(                                                                                                           
                train_model,                                                                                                
                ["example_train_x", "example_train_y", "parameters"],                                                       
                "example_model",                                                                                            
                name="train"                                                                                                
            ),                                                                                                              
            node(                                                                                                           
                predict,                                                                                                    
                dict(model="example_model", test_x="example_test_x"),                                                       
                "example_predictions",                                                                                      
                name="predict"                                                                                              
            ),                                                                                                              
            node(                                                                                                           
                report_accuracy,                                                                                            
                ["example_predictions", "example_test_y"],                                                                  
                None,                                                                                                       
                name="report"),                                                                                             
        ]                                                                                                                   
    )                                                                                                                       
                                                                                                                            
def test_pipeline(**kwargs): return Pipeline([node(lambda x: x,"example_train_x","example_model",name="test",tags="test")]  
```

Next, I want to post the result of running the below three commands and what I see when I execute them.

Actions:
1. Trying to run test_pipeline using `kedro run --pipeline test_pipeline`, which gives me the error
```
2021-03-25 04:50:43,502 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.
2021-03-25 04:50:43,598 - root - INFO - ** Kedro project check_tags
2021-03-25 04:50:43,599 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.
Traceback (most recent call last):
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/context/context.py", line 304, in _get_pipeline
    return pipelines[name]
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/dynaconf/utils/functional.py", line 17, in inner
    return func(self._wrapped, *args)
KeyError: 'test_pipeline'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/user_files/envs/kedro_tags/bin/kedro", line 10, in <module>
    sys.exit(main())
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 228, in main
    cli_collection(**cli_context)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/user_files/testing/check_tags/src/check_tags/cli.py", line 231, in run
    session.run(
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/session/session.py", line 344, in run
    pipeline = context._get_pipeline(name=pipeline_name)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/context/context.py", line 306, in _get_pipeline
    raise KedroContextError(
kedro.framework.context.context.KedroContextError: Failed to find the pipeline named 'test_pipeline'. It needs to be generated and returned by the 'register_pipelines' function.
```
2. Trying to run node named test using `kedro run --node test` which gives me the error

```
2021-03-25 04:51:23,289 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.
2021-03-25 04:51:23,384 - root - INFO - ** Kedro project check_tags
2021-03-25 04:51:23,385 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.
Traceback (most recent call last):
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/context/context.py", line 304, in _get_pipeline
    return pipelines[name]
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/dynaconf/utils/functional.py", line 17, in inner
    return func(self._wrapped, *args)
KeyError: '__default__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/user_files/envs/kedro_tags/bin/kedro", line 10, in <module>
    sys.exit(main())
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 228, in main
    cli_collection(**cli_context)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/user_files/testing/check_tags/src/check_tags/cli.py", line 231, in run
    session.run(
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/session/session.py", line 344, in run
    pipeline = context._get_pipeline(name=pipeline_name)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/context/context.py", line 306, in _get_pipeline
    raise KedroContextError(
kedro.framework.context.context.KedroContextError: Failed to find the pipeline named '__default__'. It needs to be generated and returned by the 'register_pipelines' function.
```
3. Trying to run nodes tagged with test `kedro run --tag test` which gives me the error 

```
2021-03-25 04:51:54,923 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.                       
2021-03-25 04:51:55,020 - root - INFO - ** Kedro project check_tags                                                                                           
2021-03-25 04:51:55,020 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.                          
Traceback (most recent call last):                                                                                                                            
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/context/context.py", line 304, in _get_pipeline                          
    return pipelines[name]                                                                                                                                    
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/dynaconf/utils/functional.py", line 17, in inner                                         
    return func(self._wrapped, *args)                                                                                                                         
KeyError: '__default__'                                                                                                                                       
                                                                                                                                                              
The above exception was the direct cause of the following exception:                                                                                          
                                                                                                                                                              
Traceback (most recent call last):                                                                                                                            
  File "/root/user_files/envs/kedro_tags/bin/kedro", line 10, in <module>                                                                                     
    sys.exit(main())                                                                                                                                          
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 228, in main                                           
    cli_collection(**cli_context)                                                                                                                             
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 829, in __call__                                                    
    return self.main(*args, **kwargs)                                                                                                                         
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 782, in main                                                        
    rv = self.invoke(ctx)                                                                                                                                     
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 1259, in invoke                                                     
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                                   
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 1066, in invoke                                                     
    return ctx.invoke(self.callback, **ctx.params)                                                                                                            
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 610, in invoke                                                      
    return callback(*args, **kwargs)                                                                                                                          
  File "/root/user_files/testing/check_tags/src/check_tags/cli.py", line 231, in run                                                                          
    session.run(                                                                                                                                              
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/session/session.py", line 344, in run                                    
    pipeline = context._get_pipeline(name=pipeline_name)                                                                                                      
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/context/context.py", line 306, in _get_pipeline                          
    raise KedroContextError(                                                                                                                                  
kedro.framework.context.context.KedroContextError: Failed to find the pipeline named '__default__'. It needs to be generated and returned by the 'register_pip
elines' function.                                                                                                                                             
```
So the errors in all three cases point to the register_pipeline file not being properly formatted. Which brings me back to the questions:  
1. Do I need to register every pipeline I declare in a project to be able to run the nodes? I ask this because previous kedro versions used to discover pipelines regardless of where you defined them 
2. I am unable to run the node tagged `train`, which comes by default with the kedro starter. I removed the test pipeline I added, created a new project from scratch and ran `kedro run --node train` to get the error below. Actually even `kedro run` gives me the same error here:
```
2021-03-25 04:57:15,720 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.
2021-03-25 04:57:15,817 - root - INFO - ** Kedro project check_tags
2021-03-25 04:57:15,818 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.
Traceback (most recent call last):
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/context/context.py", line 304, in _get_pipeline
    return pipelines[name]
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/dynaconf/utils/functional.py", line 17, in inner
    return func(self._wrapped, *args)
KeyError: '__default__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/user_files/envs/kedro_tags/bin/kedro", line 10, in <module>
    sys.exit(main())
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 228, in main
    cli_collection(**cli_context)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/user_files/testing/check_tags/src/check_tags/cli.py", line 231, in run
    session.run(
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/session/session.py", line 344, in run
    pipeline = context._get_pipeline(name=pipeline_name)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/context/context.py", line 306, in _get_pipeline
    raise KedroContextError(
kedro.framework.context.context.KedroContextError: Failed to find the pipeline named '__default__'. It needs to be generated and returned by the 'register_pipelines' function.
```

**Comment by WaylonWalker** [comment]
I see now, your `pipeline_registry.py` needs to import, create, and add test_pipeline to the pipelines returned.

``` diff
"""Project pipelines."""
from typing import Dict

from kedro.pipeline import Pipeline

from check_tags.pipelines import data_engineering as de
from check_tags.pipelines import data_science as ds


def register_pipelines() -> Dict[str, Pipeline]:
    """Register the project's pipelines.

    Returns:
        A mapping from a pipeline name to a ``Pipeline`` object.

    """
    data_engineering_pipeline = de.create_pipeline()
    data_science_pipeline = ds.create_pipeline()
+    test_pipeline = ds.test_pipeline()

    return {
        "de": data_engineering_pipeline,
        "ds": data_science_pipeline,
+        "test_pipeline": test_pipeline,
        "__default__": data_engineering_pipeline + data_science_pipeline,
    }
```

Can you double check your kedro version `kedro -V`? You may have the wrong env active in the last traceback it shows that its not picking up your `register_pipelines` function at all.

**Comment by roumail** [comment]
Hello @WaylonWalker, sorry for the delayed response. 

Feedback on following your suggestions:
------------------------------------------------
I added the suggested lines to my `register_pipelines.py`, (as well as correctly importing `test_pipeline` into `register_pipeline.py`, but I'm still getting the error below

```
(kedro_tags) [root@755ebdd23575 check_tags]# kedro run
2021-04-06 07:37:53,135 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.
2021-04-06 07:37:53,230 - root - INFO - ** Kedro project check_tags
2021-04-06 07:37:53,231 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.
Traceback (most recent call last):
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/context/context.py", line 304, in _get_pipeline
    return pipelines[name]
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/dynaconf/utils/functional.py", line 17, in inner
    return func(self._wrapped, *args)
KeyError: '__default__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/user_files/envs/kedro_tags/bin/kedro", line 10, in <module>
    sys.exit(main())
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 228, in main
    cli_collection(**cli_context)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/user_files/testing/check_tags/src/check_tags/cli.py", line 231, in run
    session.run(
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/session/session.py", line 344, in run
    pipeline = context._get_pipeline(name=pipeline_name)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/context/context.py", line 306, in _get_pipeline
    raise KedroContextError(
kedro.framework.context.context.KedroContextError: Failed to find the pipeline named '__default__'. It needs to be generated and returned by the 'register_pipelines' function.
(kedro_tags) [root@755ebdd23575 check_tags]# kedro run
2021-04-06 07:40:21,730 - kedro.framework.session.store - INFO - `read()` not implemented for `BaseSessionStore`. Assuming empty store.
2021-04-06 07:40:21,824 - root - INFO - ** Kedro project check_tags
2021-04-06 07:40:21,825 - kedro.framework.session.store - INFO - `save()` not implemented for `BaseSessionStore`. Skipping the step.
Traceback (most recent call last):
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/context/context.py", line 304, in _get_pipeline
    return pipelines[name]
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/dynaconf/utils/functional.py", line 17, in inner
    return func(self._wrapped, *args)
KeyError: '__default__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/user_files/envs/kedro_tags/bin/kedro", line 10, in <module>
    sys.exit(main())
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 228, in main
    cli_collection(**cli_context)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/user_files/testing/check_tags/src/check_tags/cli.py", line 231, in run
    session.run(
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/session/session.py", line 344, in run
    pipeline = context._get_pipeline(name=pipeline_name)
  File "/root/user_files/envs/kedro_tags/lib/python3.8/site-packages/kedro/framework/context/context.py", line 306, in _get_pipeline
    raise KedroContextError(
kedro.framework.context.context.KedroContextError: Failed to find the pipeline named '__default__'. It needs to be generated and returned by the 'register_pipelines' function.
```

Understanding about intended usage of `register_pipelines.py`
---------------------------------------------------------------------

Let me check that I understood you well: to be able to run a pipeline or nodes belonging to a specific pipeline using the `kedro run --tag/node`, etc, it is required that we first **register** the pipeline using `register_pipelines.py`. As mentioned, the reason I was expecting `test_pipeline` to be "auto-discovered" by `kedro run --node` is because in previous versions of kedro, we had many different `pipeline.py`'s inside the `src` directory and we were able to run any pipeline. 

Environment and steps to reproduce error above
------------------------------------------------------
As for the kedro version, it is 0.17.2 (checking using kedro -V after activating the conda env)
```
1. kedro new --starter pandas-iris
2. cd check_tags (assigned project name)
3. Add test_pipeline (as defined above):   
    a.  to `src/check_tags/pipelines/data_science/pipeline.py`
    b. to `src/check_tags/pipelines/data_science/__init__.py`
    c. to register_pipeline.py as suggested
4. kedro run
![image](https://user-images.githubusercontent.com/32498483/113677144-8dfbb200-96bd-11eb-9469-81bccee09484.png)
```

Interestingly, even if I comment test_pipeline out from `register_pipeline.py` I still get the same error about "__default__" key error. Are you able to do `kedro run` after checking out the pandas-iris starter?

**Comment by WaylonWalker** [comment]
If you are using `kedro run` you need to implement a `__default__` pipeline, if you want to run soemthing from your `test_pipeline` you need to add `--pipeline test_pipeline` to your cli command.

Can you try `kedro run --pipeline test_pipeline`?
Can you see what pipelines are being registered by running `kedro pipeline list`?

**Comment by roumail** [comment]
If you are using kedro run you need to implement a __default__ pipeline, if you want to run soemthing from your test_pipeline you need to add --pipeline test_pipeline to your cli command.
```diff
+ __default__ pipeline is already there - this is a kedro starter! see below: it's defined as data_engineering + data_science. Still running kedro run from the project root gives me the error above. I get the same error whether I run kedro run --pipeline test
```
```
"""Project pipelines."""
from typing import Dict

from kedro.pipeline import Pipeline

from check_tags.pipelines import data_engineering as de
from check_tags.pipelines import data_science as ds


def register_pipelines() -> Dict[str, Pipeline]:
    """Register the project's pipelines.

    Returns:
        A mapping from a pipeline name to a ``Pipeline`` object.

    """
    data_engineering_pipeline = de.create_pipeline()
    data_science_pipeline = ds.create_pipeline()
    # test_pipeline = ds.create_pipeline()

    return {
        "de": data_engineering_pipeline,
        "ds": data_science_pipeline,
        # "test": test_pipeline,
        "__default__": data_engineering_pipeline + data_science_pipeline,
    }

```

Can you see what pipelines are being registered by running kedro pipeline list?
```diff
+ interestingly I get an empty list..
```
