### ISSUE TITLE
Error during project creation

### ISSUE THREAD

**Issue by acnazarejr** [quantumblacklabs/kedro#800]
## Description
I'm starting on Kedro now. When I try to create a new project using `kedro new`, I'm receiving the error below.

## Context
I'm trying to create a new project.

## Steps to Reproduce
1. I install kedro using conda 
2. Type `kedro new`

## Expected Result
A new project should be created.

## Actual Result
I received the following error:

```
C:\Users\140742\Anaconda3\envs\racchurnpf\lib\site-packages\past\builtins\misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
Traceback (most recent call last):
  File "C:\Users\140742\Anaconda3\envs\racchurnpf\Scripts\kedro-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\140742\Anaconda3\envs\racchurnpf\lib\site-packages\kedro\framework\cli\cli.py", line 265, in main
    cli_collection()
  File "C:\Users\140742\Anaconda3\envs\racchurnpf\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\140742\Anaconda3\envs\racchurnpf\lib\site-packages\kedro\framework\cli\cli.py", line 210, in main
    super().main(
  File "C:\Users\140742\Anaconda3\envs\racchurnpf\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\140742\Anaconda3\envs\racchurnpf\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\140742\Anaconda3\envs\racchurnpf\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\140742\Anaconda3\envs\racchurnpf\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\140742\Anaconda3\envs\racchurnpf\lib\site-packages\kedro\framework\cli\starters.py", line 140, in new
    cookiecutter_dir = _get_cookiecutter_dir(template_path, checkout, directory, tmpdir)
  File "C:\Users\140742\Anaconda3\envs\racchurnpf\lib\site-packages\kedro\framework\cli\starters.py", line 299, in _get_cookiecutter_dir
    cookiecutter_dir, _ = determine_repo_dir(
TypeError: determine_repo_dir() got an unexpected keyword argument 'directory'
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.4
* Python version used (`python -V`): 3.8.10
* Operating system and version: Windows 10

**Comment by AntonyMilneQB** [comment]
Hello @acnazarejr and thanks for the bug report. I think this must be caused by some sort of incompatibility between the conda distribution of kedro and cookiecutter versions, but I'm not sure exactly why. 

Please could you run `cookiecutter -V` to see what version you have installed?

One easy fix, if it's possible for you, would probably be just to do `pip install kedro` rather than `conda install`.

**Comment by acnazarejr** [comment]
Hi @AntonyMilneQB, I did `pip install kedro` and works for me! Thank you!

I also checked the version of cookicutter:

`Cookiecutter 1.7.3 from /home/140742/anaconda3/lib/python3.8/site-packages (Python 3.8)`

**Comment by acnazarejr** [comment]
Hi @AntonyMilneQB, I did `pip install kedro` and works for me! Thank you!

I also checked the version of cookicutter:

`Cookiecutter 1.7.3 from /home/user/anaconda3/lib/python3.8/site-packages (Python 3.8)`
