### ISSUE TITLE
Cannot add pandera.check_io decorator to node function

### ISSUE THREAD

**Issue by clstaudt** [quantumblacklabs/kedro#821]
## Description
I want to use [pandera decorators](https://pandera.readthedocs.io/en/latest/decorators.html) to check whether inputs and outputs of a node function conform to a DataFrameSchema.

Example: Adding this decorator to a node function....

```
@pandera.check_io(data=schema.bom, out=schema.bom)
def repair_BOM(data: pandas.DataFrame, params) -> pandas.DataFrame:
```

## Expected Result

It should be possible to add pandera schema validation decorators to Kedro node functions.

## Actual Result

```
/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/fsspec/implementations/local.py:29: FutureWarning: The default value of auto_mkdir=True has been deprecated and will be changed to auto_mkdir=False by default in a future release.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/cls/miniforge3/envs/packaging-measurement/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 725, in main
    cli_collection()
  File "/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cls/Documents/Work/Projects/Client/packaging-measurement/kedro_cli.py", line 222, in run
    context.run(
  File "/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/kedro/framework/context/context.py", line 767, in run
    raise exc
  File "/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/kedro/framework/context/context.py", line 759, in run
    run_result = runner.run(filtered_pipeline, catalog, run_id)
  File "/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/kedro/runner/runner.py", line 101, in run
    self._run(pipeline, catalog, run_id)
  File "/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/kedro/runner/parallel_runner.py", line 285, in _run
    self._validate_nodes(nodes)
  File "/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/site-packages/kedro/runner/parallel_runner.py", line 197, in _validate_nodes
    ForkingPickler.dumps(node)
  File "/Users/cls/miniforge3/envs/packaging-measurement/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
NotImplementedError: object proxy must define __reduce_ex__()
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): kedro, version 0.16.6
* Python version used (`python -V`): Python 3.8.8
* Operating system and version: macOS 11.4

**Comment by datajoely** [comment]
Hi @clstaudt I noticed part of the stack trace is using giving a serialisation error using `MultiProcessing` and `ParallelRunner` - does this work if you use `SequentialRuner`?

**Comment by clstaudt** [comment]
@datajoely  Indeed it work with `kedro run` without `--parallel`.  However, I think `--parallel` is one of the most important arguments for using kedro in the first place.

**Comment by datajoely** [comment]
> @datajoely  Indeed it works with `kedro run` without `--parallel`.  However, for me `--parallel` is one of the most important reasons for using kedro in the first place.

Hi @clstaudt - thanks for testing this for us. Now at least we know it's a process serialisation issue that we can get to the bottom of. Will look into it on Monday :)

**Comment by clstaudt** [comment]
@datajoely  Thanks for looking into this. Would appreciate an update: Is there a quick fix coming or should I invest in a workaround ( maybe a decorator that only runs the pandera schema check if using the sequential runner...)?

**Comment by datajoely** [comment]
> @datajoely  Thanks for looking into this. Would appreciate an update: Is there a quick fix coming or should I invest in a workaround ( maybe a decorator that only runs the pandera schema check if using the sequential runner...)?

I can't answer this right now - we need to investigate what's going on in the pandera decorator.

**Comment by datajoely** [comment]
Hi @clstaudt - I've looked into this and have an update. `ParallelRunner` uses `multiprocessing` behind the scenes which requires pickling the functions and [this won't work](https://newbedev.com/python-decorator-with-multiprocessing-fails) in general. 

In terms of solutions I see two options:

1. Use the non-decorator [implementation of Pandera validation](https://pandera.readthedocs.io/en/latest/dataframe_schemas.html), not as pretty as decorators but functionally the same.
2. Use great-expectations, we have a sample implementation [here in the docs](
https://kedro.readthedocs.io/en/latest/07_extend_kedro/02_hooks.html#add-data-validation).

**Comment by datajoely** [comment]
I'm going to close this issue - please re-open if you need anything else
