### ISSUE TITLE
[KED-2751] `kedro new` command not working for conda python3.8

### ISSUE THREAD

**Issue by redaelhail** [quantumblacklabs/kedro#823]
## Description
Short description of the problem here.

## Context
I was trying to create a new project with Kedro new

## Steps to Reproduce
Install kedro with `conda install -c conda-forge kedro`
type `Kedro new` in the terminal

## Expected Result
I should be asked to enter each of the following variables in turn (project_name, repo_name, package_name)

## Actual Result
What happens is that I get this error:

```
/opt/homebrew/Caskroom/miniforge/base/envs/har/lib/python3.8/site-packages/past/builtins/misc.py:45: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/har/bin/kedro", line 10, in <module>
    sys.exit(main())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/har/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 265, in main
    cli_collection()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/har/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/har/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 210, in main
    super().main(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/har/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/har/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniforge/base/envs/har/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/har/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/har/lib/python3.8/site-packages/kedro/framework/cli/starters.py", line 140, in new
    cookiecutter_dir = _get_cookiecutter_dir(template_path, checkout, directory, tmpdir)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/har/lib/python3.8/site-packages/kedro/framework/cli/starters.py", line 299, in _get_cookiecutter_dir
    cookiecutter_dir, _ = determine_repo_dir(
TypeError: determine_repo_dir() got an unexpected keyword argument 'directory'
```

## Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used :0.17.4
* Python version used :Python 3.8.10
* Operating system and version: Macbook M1, version 11.2

**Comment by MerelTheisenQB** [comment]
Hi @redaelhail, thanks for reporting this. I've managed to replicate the bug, so I'll create a ticket for us to fix it 🐛 

As a workaround for now you can uninstall kedro from conda and re-install it using pip:
`conda remove kedro`
`pip install kedro`

**Comment by redaelhail** [comment]
This solved my problem, thank you!

**Comment by SajidAlamQB** [comment]
This is an issue with using cookiecutter 1.7.0. To resolve this either use `conda install kedro==0.17.5` or install latest cookiecutter then kedro 0.17.4. Otherwise use `pip` instead of `conda`.
