### ISSUE TITLE
Kedro CLI bug

### ISSUE THREAD

**Issue by matheus695p** [quantumblacklabs/kedro#863]
## Description
Problem installing kedro in an anaconda environment.

## Context
The environment does not recognise the kedro command, even a simple kedro --version.

## Steps to Reproduce
1. Anaconda environment
2. python 3.8
3. kedro version --> kedro[pyspark]==0.17.3
4. requirements below:
```zh
kedro[pyspark]==0.17.3
aiofiles==0.6.0
databricks-connect==8.1.7
et-xmlfile==1.1.0
fastapi==0.65.2
greenlet==1.1.0
grpcio==1.38.0
h11==0.12.0
kedro-viz==3.12.1
libcst==0.3.19
numexpr==2.7.3
oauthlib==3.1.1
openpyxl==3.0.7
pandas-gbq==0.15.0
proto-plus==1.18.1
protobuf==3.17.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydantic==1.8.2
pydata-google-auth==1.2.0
requests-oauthlib==1.3.0
rsa==4.7.2
semver==2.13.0
sqlalchemy==1.4.17
starlette==0.14.2
tables==3.6.1
typing-inspect==0.7.1
uvicorn==0.13.4
xlrd==1.2.0
xlsxwriter==1.4.3
xgboost==1.3.3
tk==0.1.0
toml==0.10.2
toposort==1.5
tqdm==4.61.1
traitlets==5.0.5
typing_extensions==3.10.0.0
unidecode==1.2.0
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==0.57.0
zipp==3.4.1
zstd==1.4.9.0
simplejson==3.17.3
zstd==1.4.9
PyYAML==5.4.1
pyparsing==2.4.7
pyrsistent==0.17.3
pysocks==1.7.1
python-dateutil
python-json-logger
python-slugify==5.0.2
pyyaml==5.4.1
scikit-learn==0.23.2
shap==0.39.0
slicer==0.0.7
sniffio==1.2.0
terminado==0.10.0
testpath==0.5.0
text-unidecode==1.3
threadpoolctl==2.1.0
matplotlib-inline==0.1.2
mistune==0.8.4
mkl==2021.2.0
mypy_extensions==0.4.3
nbclassic==0.3.1
nbclient==0.5.3
nbformat==5.1.3
nest-asyncio==1.5.1
notebook==6.4.0
numba==0.53.1
olefile==0.46
packaging==20.9
pexpect==4.8.0
pickleshare==0.7.5
pillow==8.2.0
pip-tools==5.5.0
pluggy==0.13.1
poyo==0.5.0
prometheus_client==0.11.0
pycparser==2.20
ipython_genutils
jinja2-time
jmespath==0.10.0
joblib==0.17.0
json5==0.9.5
jsonschema==3.2.0
jupyter_server==1.8.0
jupyterlab_pygments==0.1.2
jupyterlab_server==2.6.0
kedro==0.17.3
llvmlite==0.36.0
anyconfig==0.10.1
anyio==3.1.0
appdirs==1.4.4
appnope==0.1.2
argon2-cffi==20.1.0
async_generator==1.10
attrs==21.2.0
babel==2.9.1
backcall==0.2.0
backports.functools_lru_cache==1.6.4
binaryornot==0.4.4
black==19.10b0
brotlipy==0.7.0
cachetools==4.2.2
click==7.1.2
cloudpickle==1.6.0
cookiecutter==1.7.3
cycler==0.10.0
defusedxml==0.7.1
dynaconf==3.1.4
entrypoints==0.3
fsspec==0.8.7
gitdb==4.0.7
idna==2.10
intel-openmp==2021.2.0
lightgbm==3.2.1
catboost==0.26
s3fs==0.4.2
nbstripout==0.3.3
pytest-cov~=2.5
pytest-mock>=1.7.1, <2.0
pytest~=6.1.2
scipy==1.7.0
statsmodels==0.12.2

```

## Expected Result
 Can use kedro commands.

## Actual Result

```
Traceback (most recent call last):
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/kedro/framework/cli/utils.py", line 380, in load_entry_points
    entry_point_commands.append(entry_point.load())
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/kedro_viz/launchers/cli.py", line 35, in <module>
    from kedro_viz.server import run_server
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/kedro_viz/server.py", line 33, in <module>
    import uvicorn
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/uvicorn/__init__.py", line 2, in <module>
    from uvicorn.main import Server, main, run
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/uvicorn/main.py", line 283, in <module>
    def main(
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/click/decorators.py", line 170, in decorator
    _param_memo(f, OptionClass(param_decls, **attrs))
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/click/core.py", line 1460, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'hidden'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 268, in main
    cli_collection = KedroCLI(project_path=Path.cwd())
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 185, in __init__
    ("Global commands", self.global_groups),
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/kedro/framework/cli/cli.py", line 223, in global_groups
    return [cli, create_cli, *load_entry_points("global")]
  File "/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/lib/python3.8/site-packages/kedro/framework/cli/utils.py", line 382, in load_entry_points
    raise KedroCliError(f"Loading {name} commands from {entry_point}") from exc
kedro.framework.cli.utils.KedroCliError: Loading global commands from kedro-viz = kedro_viz.launchers.cli:commands
```

## Your Environment

* Kedro version used: 0.17.3 [pyspark]
* Python version used: 3.8
* Operating system and version: Mac OS Catalina version 10.15.7

**Comment by datajoely** [comment]
So a common reason that this can happen is due to multiple versions of Kedro being installed in different environments. Would you mind typing `which kedro` and seeing which path to the library pops up?

**Comment by matheus695p** [comment]
Hi, thanks for answer. 

```
$ wich kedro
/Users/matheuspintoarratia/opt/anaconda3/envs/ml-an/bin/kedro
```
My solution was to remove all environments with another version of kedro. I don't think it's the best solution, but it worked for me. Why are different versions of kedro incompatible in different environments, they share some path in the cli?

**Comment by datajoely** [comment]
Hi @matheus695p this is a more of python / terminal issue than a Kedro one. We have the answer to hand because it comes up relatively frequently.  My only advice to mitigate this is to be either (1) be super organised with your virtual environments (2) work in a docker container so everything is isolated and reproducible from scratch.
