### ISSUE TITLE
kedro application not running on aws batch job

### ISSUE THREAD

**Issue by ibakayoko** [quantumblacklabs/kedro#965]
## Description
Dockerized kedro application not running on AWS Batch

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce
1. Dockerize kedro application
2. Create Batch (compute, job definition, queue)
3. Run batch job

## Expected Result
AWS Batch job should run

## Actual Result
2021-10-14 15:41:52,491 - kedro.io.data_catalog - INFO - Loading data from `raw_dim_mgh_sbd` (SparkDataSetLocalStage)...
Exception in thread "main" java.lang.ExceptionInInitializerError
at org.apache.spark.SparkConf$.<init>(SparkConf.scala:714)
at org.apache.spark.SparkConf$.<clinit>(SparkConf.scala)
at org.apache.spark.SparkConf.set(SparkConf.scala:94)
at org.apache.spark.SparkConf.set(SparkConf.scala:83)
at org.apache.spark.deploy.SparkSubmit$$anonfun$prepareSubmitEnvironment$1.apply(SparkSubmit.scala:333)
at org.apache.spark.deploy.SparkSubmit$$anonfun$prepareSubmitEnvironment$1.apply(SparkSubmit.scala:333)
at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
at scala.collection.mutable.HashMap.foreach(HashMap.scala:130)
at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:333)
at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:143)
at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
**Caused by: java.net.UnknownHostException: ip-10-0-1-124.ec2.internal: ip-10-0-1-124.ec2.internal: Name or service not known**
at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
at org.apache.spark.util.Utils$.findLocalInetAddress(Utils.scala:946)
at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress$lzycompute(Utils.scala:939)
at org.apache.spark.util.Utils$.org$apache$spark$util$Utils$$localIpAddress(Utils.scala:939)
at org.apache.spark.util.Utils$$anonfun$localCanonicalHostName$1.apply(Utils.scala:996)
at org.apache.spark.util.Utils$$anonfun$localCanonicalHostName$1.apply(Utils.scala:996)
at scala.Option.getOrElse(Option.scala:121)
at org.apache.spark.util.Utils$.localCanonicalHostName(Utils.scala:996)
at org.apache.spark.internal.config.package$.<init>(package.scala:296)
at org.apache.spark.internal.config.package$.<clinit>(package.scala)
... 17 more
**Caused by: java.net.UnknownHostException: ip-10-0-1-124.ec2.internal: Name or service not known**
at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
... 26 more
2021-10-14 15:41:53,501 - kedro.runner.sequential_runner - WARNING - There are 45 nodes that have not run.

```

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.15.9
* Python version used (`python -V`): 3.6
* Operating system and version: Amazon Linux 2

**Comment by datajoely** [comment]
Hi @ibakayoko it's a little difficult to work out what's going on here - it's a Spark JVM issue not a Kedro one per se.

I guess I would start by making sure your `spark.yml` is sensible, do any other datasets of the custom `SparkDataSetLocalStage` class work?
